// Code generated by gogen. DO NOT EDIT.
package basic

import "errors"

// ================ stateflow ================

// 流程图：
// ```
// Created ──▶ Paid ──▶ Shipped ──▶ Delivered ──▶ Completed
// ```

// OrderPhase 阶段枚举
type OrderPhase string

const (
	OrderPhaseCreated   OrderPhase = "Created"
	OrderPhasePaid      OrderPhase = "Paid"
	OrderPhaseShipped   OrderPhase = "Shipped"
	OrderPhaseDelivered OrderPhase = "Delivered"
	OrderPhaseCompleted OrderPhase = "Completed"
)

var OrderPhaseEnums = struct {
	Created   OrderPhase
	Paid      OrderPhase
	Shipped   OrderPhase
	Delivered OrderPhase
	Completed OrderPhase
}{
	Created:   OrderPhaseCreated,
	Paid:      OrderPhasePaid,
	Shipped:   OrderPhaseShipped,
	Delivered: OrderPhaseDelivered,
	Completed: OrderPhaseCompleted,
}

// OrderStage 阶段（Phase + Status）
type OrderStage = OrderPhase

// 预定义阶段
var (
	StageOrderCreated   = OrderPhaseCreated
	StageOrderPaid      = OrderPhasePaid
	StageOrderShipped   = OrderPhaseShipped
	StageOrderDelivered = OrderPhaseDelivered
	StageOrderCompleted = OrderPhaseCompleted
)

// OrderState 完整状态
type OrderState struct {
	Current OrderStage `json:"current"`
}

// OrderStateColumns 数据库存储结构
type OrderStateColumns struct {
	Phase OrderPhase `gorm:"column:phase" json:"phase"`
}

func (s OrderState) ToColumns() OrderStateColumns {
	return OrderStateColumns{
		Phase: s.Current,
	}
}

func (c OrderStateColumns) ToState() OrderState {
	return OrderState{
		Current: c.Phase,
	}
}

// 错误定义
var ErrOrderInvalidTransition = errors.New("invalid transition")

func (s OrderState) TransitionTo(to OrderStage) (OrderState, error) {
	switch s.Current {
	case StageOrderCreated:
		switch to {
		case StageOrderPaid:
			return OrderState{Current: to}, nil
		}
	case StageOrderPaid:
		switch to {
		case StageOrderShipped:
			return OrderState{Current: to}, nil
		}
	case StageOrderShipped:
		switch to {
		case StageOrderDelivered:
			return OrderState{Current: to}, nil
		}
	case StageOrderDelivered:
		switch to {
		case StageOrderCompleted:
			return OrderState{Current: to}, nil
		}
	}
	return s, ErrOrderInvalidTransition
}

func (s OrderState) ValidTransitions() []OrderStage {
	switch s.Current {
	case StageOrderCreated:
		return []OrderStage{StageOrderPaid}
	case StageOrderPaid:
		return []OrderStage{StageOrderShipped}
	case StageOrderShipped:
		return []OrderStage{StageOrderDelivered}
	case StageOrderDelivered:
		return []OrderStage{StageOrderCompleted}
	}
	return nil
}

func (s OrderState) Next() []OrderState {
	var result []OrderState
	for _, stage := range s.ValidTransitions() {
		result = append(result, OrderState{Current: stage})
	}
	return result
}
