// Code generated by gogen. DO NOT EDIT.
package testdata

import "io"

// ================ templategen ================

// MyServiceMethods 为 MyService 生成的方法

func (s *MyService) GetReader() io.Reader {
	return s.reader
}

// Timeout: 30s
func (s *MyService) GetTimeout() string {
	return "30s"
}

// DeleteWithAuth 添加权限检查
// Permission: admin
// Audit: true
func (s *MyService) DeleteWithAuth(id string) error {
	// Permission check: admin
	// Audit logging enabled
	return s.Delete(id)
}

// GetWithAuth 添加权限检查
// Permission: user
// Audit: false
func (s *MyService) GetWithAuth(id string) (any, error) {
	// Permission check: user
	return s.Get(id)
}
