// Code generated by gogen. DO NOT EDIT.
package embedded

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type ArticleSchemaType struct {
	ID        gsql.IntField[uint64]
	Title     gsql.StringField[string]
	Content   gsql.StringField[string]
	CreatedBy gsql.StringField[string]
	CreatedAt gsql.DateTimeField[time.Time]
	UpdatedBy gsql.StringField[string]
	UpdatedAt gsql.DateTimeField[time.Time]
	fieldType Article
	alias     string
	tableName string
}

func (t ArticleSchemaType) TableName() string {
	return t.tableName
}

func (t ArticleSchemaType) Alias() string {
	return t.alias
}

func (t *ArticleSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Title = t.Title.WithTable(&tn)
	t.Content = t.Content.WithTable(&tn)
	t.CreatedBy = t.CreatedBy.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedBy = t.UpdatedBy.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
}

func (t ArticleSchemaType) As(alias string) ArticleSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ArticleSchemaType) ModelType() *Article {
	return &t.fieldType
}

func (t ArticleSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ArticleSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Title,
		t.Content,
		t.CreatedBy,
		t.CreatedAt,
		t.UpdatedBy,
		t.UpdatedAt,
	}
}

func (t ArticleSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ArticleSchema = ArticleSchemaType{
	tableName: "articles",
	ID:        gsql.IntFieldOf[uint64]("articles", "id", field.FlagPrimaryKey),
	Title:     gsql.StringFieldOf[string]("articles", "title"),
	Content:   gsql.StringFieldOf[string]("articles", "content"),
	CreatedBy: gsql.StringFieldOf[string]("articles", "audit_created_by"),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("articles", "audit_created_at"),
	UpdatedBy: gsql.StringFieldOf[string]("articles", "audit_updated_by"),
	UpdatedAt: gsql.DateTimeFieldOf[time.Time]("articles", "audit_updated_at"),
	fieldType: Article{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	CreatedAt gsql.DateTimeField[time.Time]
	UpdatedAt gsql.DateTimeField[time.Time]
	Name      gsql.StringField[string]
	Email     gsql.StringField[string]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.Name,
		t.Email,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("users", "created_at"),
	UpdatedAt: gsql.DateTimeFieldOf[time.Time]("users", "updated_at"),
	Name:      gsql.StringFieldOf[string]("users", "name"),
	Email:     gsql.StringFieldOf[string]("users", "email"),
	fieldType: User{},
}
