// Code generated by gogen. DO NOT EDIT.
package complextypes

import "time"

// ================ omitgen ================

// DocumentPublic 从 Document Omit 生成
type DocumentPublic struct {
	ID        uint64         `json:"id" gorm:"primaryKey"`
	Title     string         `json:"title" gorm:"column:title;size:255"`
	Content   string         `json:"content" gorm:"column:content;type:text"`
	Status    Status         `json:"status" gorm:"column:status;size:20"`
	Metadata  Metadata       `json:"metadata" gorm:"column:metadata;type:json"`
	Tags      []string       `json:"tags" gorm:"column:tags;type:json"`
	Extra     map[string]any `json:"extra" gorm:"column:extra;type:json"`
	CreatedAt time.Time      `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time      `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Document 复制字段值
func (t *DocumentPublic) From(src *Document) {
	t.ID = src.ID
	t.Title = src.Title
	t.Content = src.Content
	t.Status = src.Status
	t.Metadata = src.Metadata
	t.Tags = src.Tags
	t.Extra = src.Extra
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewDocumentPublic 从 Document 创建 DocumentPublic
func NewDocumentPublic(src *Document) DocumentPublic {
	var result DocumentPublic
	result.From(src)
	return result
}

// EventPublic 从 Event Omit 生成
type EventPublic struct {
	ID          uint64     `json:"id" gorm:"primaryKey"`
	Type        string     `json:"type" gorm:"column:type;size:50"`
	Payload     any        `json:"payload" gorm:"column:payload;type:json"`
	Timestamp   time.Time  `json:"timestamp" gorm:"column:timestamp"`
	ProcessedAt *time.Time `json:"processed_at" gorm:"column:processed_at"`
}

// From 从 Event 复制字段值
func (t *EventPublic) From(src *Event) {
	t.ID = src.ID
	t.Type = src.Type
	t.Payload = src.Payload
	t.Timestamp = src.Timestamp
	t.ProcessedAt = src.ProcessedAt
}

// NewEventPublic 从 Event 创建 EventPublic
func NewEventPublic(src *Event) EventPublic {
	var result EventPublic
	result.From(src)
	return result
}

// ================ pickgen ================

// DocumentBasic 从 Document Pick 生成
type DocumentBasic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Title     string    `json:"title" gorm:"column:title;size:255"`
	Status    Status    `json:"status" gorm:"column:status;size:20"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
}

// From 从 Document 复制字段值
func (t *DocumentBasic) From(src *Document) {
	t.ID = src.ID
	t.Title = src.Title
	t.Status = src.Status
	t.CreatedAt = src.CreatedAt
}

// NewDocumentBasic 从 Document 创建 DocumentBasic
func NewDocumentBasic(src *Document) DocumentBasic {
	var result DocumentBasic
	result.From(src)
	return result
}

// EventBasic 从 Event Pick 生成
type EventBasic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Type      string    `json:"type" gorm:"column:type;size:50"`
	Timestamp time.Time `json:"timestamp" gorm:"column:timestamp"`
}

// From 从 Event 复制字段值
func (t *EventBasic) From(src *Event) {
	t.ID = src.ID
	t.Type = src.Type
	t.Timestamp = src.Timestamp
}

// NewEventBasic 从 Event 创建 EventBasic
func NewEventBasic(src *Event) EventBasic {
	var result EventBasic
	result.From(src)
	return result
}
