// Code generated by gogen. DO NOT EDIT.
package basic

import (
	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type OrderSchemaType struct {
	ID          gsql.IntField[uint64]
	UserID      gsql.IntField[uint64]
	TotalAmount gsql.FloatField[float64]
	Discount    gsql.FloatField[float32]
	Status      gsql.IntField[int8]
	fieldType   Order
	alias       string
	tableName   string
}

func (t OrderSchemaType) TableName() string {
	return t.tableName
}

func (t OrderSchemaType) Alias() string {
	return t.alias
}

func (t *OrderSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
	t.TotalAmount = t.TotalAmount.WithTable(&tn)
	t.Discount = t.Discount.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
}

func (t OrderSchemaType) As(alias string) OrderSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderSchemaType) ModelType() *Order {
	return &t.fieldType
}

func (t OrderSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.UserID,
		t.TotalAmount,
		t.Discount,
		t.Status,
	}
}

func (t OrderSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderSchema = OrderSchemaType{
	tableName:   "orders",
	ID:          gsql.IntFieldOf[uint64]("orders", "id", field.FlagPrimaryKey),
	UserID:      gsql.IntFieldOf[uint64]("orders", "user_id"),
	TotalAmount: gsql.FloatFieldOf[float64]("orders", "total_amount"),
	Discount:    gsql.FloatFieldOf[float32]("orders", "discount"),
	Status:      gsql.IntFieldOf[int8]("orders", "status"),
	fieldType:   Order{},
}

type ProductSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Price     gsql.IntField[int64]
	Stock     gsql.IntField[int32]
	Category  gsql.IntField[uint8]
	Weight    gsql.IntField[uint16]
	fieldType Product
	alias     string
	tableName string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
	t.Stock = t.Stock.WithTable(&tn)
	t.Category = t.Category.WithTable(&tn)
	t.Weight = t.Weight.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Price,
		t.Stock,
		t.Category,
		t.Weight,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName: "products",
	ID:        gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("products", "name"),
	Price:     gsql.IntFieldOf[int64]("products", "price"),
	Stock:     gsql.IntFieldOf[int32]("products", "stock"),
	Category:  gsql.IntFieldOf[uint8]("products", "category"),
	Weight:    gsql.IntFieldOf[uint16]("products", "weight"),
	fieldType: Product{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Email     gsql.StringField[string]
	Age       gsql.IntField[int]
	Score     gsql.FloatField[float64]
	IsActive  gsql.IntField[bool]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Age = t.Age.WithTable(&tn)
	t.Score = t.Score.WithTable(&tn)
	t.IsActive = t.IsActive.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.Age,
		t.Score,
		t.IsActive,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("users", "name"),
	Email:     gsql.StringFieldOf[string]("users", "email"),
	Age:       gsql.IntFieldOf[int]("users", "age"),
	Score:     gsql.FloatFieldOf[float64]("users", "score"),
	IsActive:  gsql.IntFieldOf[bool]("users", "is_active"),
	fieldType: User{},
}
