// Code generated by gogen. DO NOT EDIT.
package decimal_types

import (
	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type AccountSchemaType struct {
	ID           gsql.IntField[uint64]
	UserID       gsql.IntField[uint64]
	Balance      gsql.DecimalField[float64]
	CreditLimit  gsql.DecimalField[float64]
	InterestRate gsql.DecimalField[float64]
	Status       gsql.IntField[int]
	fieldType    Account
	alias        string
	tableName    string
}

func (t AccountSchemaType) TableName() string {
	return t.tableName
}

func (t AccountSchemaType) Alias() string {
	return t.alias
}

func (t *AccountSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
	t.Balance = t.Balance.WithTable(&tn)
	t.CreditLimit = t.CreditLimit.WithTable(&tn)
	t.InterestRate = t.InterestRate.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
}

func (t AccountSchemaType) As(alias string) AccountSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t AccountSchemaType) ModelType() *Account {
	return &t.fieldType
}

func (t AccountSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t AccountSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.UserID,
		t.Balance,
		t.CreditLimit,
		t.InterestRate,
		t.Status,
	}
}

func (t AccountSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var AccountSchema = AccountSchemaType{
	tableName:    "accounts",
	ID:           gsql.IntFieldOf[uint64]("accounts", "id", field.FlagPrimaryKey),
	UserID:       gsql.IntFieldOf[uint64]("accounts", "user_id", field.FlagIndex),
	Balance:      gsql.DecimalFieldOf[float64]("accounts", "balance"),
	CreditLimit:  gsql.DecimalFieldOf[float64]("accounts", "credit_limit"),
	InterestRate: gsql.DecimalFieldOf[float64]("accounts", "interest_rate"),
	Status:       gsql.IntFieldOf[int]("accounts", "status"),
	fieldType:    Account{},
}

type PriceSchemaType struct {
	ID          gsql.IntField[uint64]
	ProductName gsql.StringField[string]
	Amount      gsql.DecimalField[float64]
	TaxRate     gsql.DecimalField[string]
	Discount    gsql.DecimalField[float64]
	Total       gsql.DecimalField[float64]
	fieldType   Price
	alias       string
	tableName   string
}

func (t PriceSchemaType) TableName() string {
	return t.tableName
}

func (t PriceSchemaType) Alias() string {
	return t.alias
}

func (t *PriceSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.ProductName = t.ProductName.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.TaxRate = t.TaxRate.WithTable(&tn)
	t.Discount = t.Discount.WithTable(&tn)
	t.Total = t.Total.WithTable(&tn)
}

func (t PriceSchemaType) As(alias string) PriceSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t PriceSchemaType) ModelType() *Price {
	return &t.fieldType
}

func (t PriceSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t PriceSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.ProductName,
		t.Amount,
		t.TaxRate,
		t.Discount,
		t.Total,
	}
}

func (t PriceSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var PriceSchema = PriceSchemaType{
	tableName:   "prices",
	ID:          gsql.IntFieldOf[uint64]("prices", "id", field.FlagPrimaryKey),
	ProductName: gsql.StringFieldOf[string]("prices", "product_name"),
	Amount:      gsql.DecimalFieldOf[float64]("prices", "amount"),
	TaxRate:     gsql.DecimalFieldOf[string]("prices", "tax_rate"),
	Discount:    gsql.DecimalFieldOf[float64]("prices", "discount"),
	Total:       gsql.DecimalFieldOf[float64]("prices", "total"),
	fieldType:   Price{},
}
