// Code generated by gogen. DO NOT EDIT.
package crossref

import (
	"github.com/donutnomad/gogen/pickgen/examples/basic"
	"github.com/donutnomad/gogen/pickgen/examples/embedded"
	specialpkg "github.com/donutnomad/gogen/pickgen/examples/special-pkg"
	v2api "github.com/donutnomad/gogen/pickgen/examples/v2-api"
)

// ================ pickgen ================

// ConfigKey 从 Config Pick 生成
type ConfigKey struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Key   string `json:"key" gorm:"column:key;uniqueIndex"`
	Value string `json:"value" gorm:"column:value"`
}

// From 从 specialpkg.Config 复制字段值
func (t *ConfigKey) From(src *specialpkg.Config) {
	t.ID = src.ID
	t.Key = src.Key
	t.Value = src.Value
}

// NewConfigKey 从 specialpkg.Config 创建 ConfigKey
func NewConfigKey(src *specialpkg.Config) ConfigKey {
	var result ConfigKey
	result.From(src)
	return result
}

// EmployeeID 从 Employee Pick 生成
type EmployeeID struct {
	ID   uint64 `json:"id" gorm:"primaryKey"`
	Name string `json:"name" gorm:"column:name;size:100"`
}

// From 从 embedded.Employee 复制字段值
func (t *EmployeeID) From(src *embedded.Employee) {
	t.ID = src.ID
	t.Name = src.Name
}

// NewEmployeeID 从 embedded.Employee 创建 EmployeeID
func NewEmployeeID(src *embedded.Employee) EmployeeID {
	var result EmployeeID
	result.From(src)
	return result
}

// ProductPrice 从 Product Pick 生成
type ProductPrice struct {
	ID    uint64  `json:"id" gorm:"primaryKey"`
	Name  string  `json:"name" gorm:"column:name;size:200"`
	Price float64 `json:"price" gorm:"column:price"`
}

// From 从 basic.Product 复制字段值
func (t *ProductPrice) From(src *basic.Product) {
	t.ID = src.ID
	t.Name = src.Name
	t.Price = src.Price
}

// NewProductPrice 从 basic.Product 创建 ProductPrice
func NewProductPrice(src *basic.Product) ProductPrice {
	var result ProductPrice
	result.From(src)
	return result
}

// RequestID 从 Request Pick 生成
type RequestID struct {
	ID     string `json:"id"`
	Method string `json:"method"`
	Path   string `json:"path"`
}

// From 从 v2api.Request 复制字段值
func (t *RequestID) From(src *v2api.Request) {
	t.ID = src.ID
	t.Method = src.Method
	t.Path = src.Path
}

// NewRequestID 从 v2api.Request 创建 RequestID
func NewRequestID(src *v2api.Request) RequestID {
	var result RequestID
	result.From(src)
	return result
}

// UserID 从 User Pick 生成
type UserID struct {
	ID uint64 `json:"id" gorm:"primaryKey"`
}

// From 从 basic.User 复制字段值
func (t *UserID) From(src *basic.User) {
	t.ID = src.ID
}

// NewUserID 从 basic.User 创建 UserID
func NewUserID(src *basic.User) UserID {
	var result UserID
	result.From(src)
	return result
}
