// Code generated by gogen. DO NOT EDIT.
package complex_types

import "net/http"

// ================ templategen ================

// UserHandler Routes
// Base path: /api/v1/users
// Version: 1.0

func RegisterUserHandlerRoutes(mux *http.ServeMux, handler *UserHandler) {
	// GET /api/v1/users/list
	// Requires authentication
	mux.HandleFunc("GET /api/v1/users/list", handler.List)
	// POST /api/v1/users/create
	// Requires authentication
	mux.HandleFunc("POST /api/v1/users/create", handler.Create)
	// GET /api/v1/users/{id}
	mux.HandleFunc("GET /api/v1/users/{id}", handler.GetByID)
}
