// Code generated by gogen. DO NOT EDIT.
package indexes

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type OrderSchemaType struct {
	ID          gsql.IntField[uint64]
	OrderNo     gsql.StringField[string]
	UserID      gsql.IntField[uint64]
	Status      gsql.IntField[int]
	TotalAmount gsql.FloatField[float64]
	CreatedAt   gsql.DateTimeField[time.Time]
	fieldType   Order
	alias       string
	tableName   string
}

func (t OrderSchemaType) TableName() string {
	return t.tableName
}

func (t OrderSchemaType) Alias() string {
	return t.alias
}

func (t *OrderSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.OrderNo = t.OrderNo.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
	t.TotalAmount = t.TotalAmount.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t OrderSchemaType) As(alias string) OrderSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderSchemaType) ModelType() *Order {
	return &t.fieldType
}

func (t OrderSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.OrderNo,
		t.UserID,
		t.Status,
		t.TotalAmount,
		t.CreatedAt,
	}
}

func (t OrderSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderSchema = OrderSchemaType{
	tableName:   "orders",
	ID:          gsql.IntFieldOf[uint64]("orders", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	OrderNo:     gsql.StringFieldOf[string]("orders", "order_no", field.FlagUniqueIndex),
	UserID:      gsql.IntFieldOf[uint64]("orders", "user_id", field.FlagIndex),
	Status:      gsql.IntFieldOf[int]("orders", "status", field.FlagIndex),
	TotalAmount: gsql.FloatFieldOf[float64]("orders", "total_amount"),
	CreatedAt:   gsql.DateTimeFieldOf[time.Time]("orders", "created_at", field.FlagIndex),
	fieldType:   Order{},
}

type ProductSchemaType struct {
	ID         gsql.IntField[uint64]
	SKU        gsql.StringField[string]
	CategoryID gsql.IntField[uint64]
	Name       gsql.StringField[string]
	Price      gsql.FloatField[float64]
	fieldType  Product
	alias      string
	tableName  string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.SKU = t.SKU.WithTable(&tn)
	t.CategoryID = t.CategoryID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.SKU,
		t.CategoryID,
		t.Name,
		t.Price,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName:  "products",
	ID:         gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey),
	SKU:        gsql.StringFieldOf[string]("products", "sku", field.FlagUniqueIndex),
	CategoryID: gsql.IntFieldOf[uint64]("products", "category_id", field.FlagIndex),
	Name:       gsql.StringFieldOf[string]("products", "name"),
	Price:      gsql.FloatFieldOf[float64]("products", "price"),
	fieldType:  Product{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	Username  gsql.StringField[string]
	Email     gsql.StringField[string]
	Phone     gsql.StringField[string]
	Status    gsql.IntField[int]
	CreatedAt gsql.DateTimeField[time.Time]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Username = t.Username.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Phone = t.Phone.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Username,
		t.Email,
		t.Phone,
		t.Status,
		t.CreatedAt,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Username:  gsql.StringFieldOf[string]("users", "username", field.FlagUniqueIndex),
	Email:     gsql.StringFieldOf[string]("users", "email", field.FlagUniqueIndex),
	Phone:     gsql.StringFieldOf[string]("users", "phone", field.FlagIndex),
	Status:    gsql.IntFieldOf[int]("users", "status", field.FlagIndex),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("users", "created_at", field.FlagIndex),
	fieldType: User{},
}
