// Code generated by gogen. DO NOT EDIT.
package no_status

import "errors"

// ================ stateflow ================

// PaymentPhase 阶段枚举
type PaymentPhase string

const (
	PaymentPhasePending    PaymentPhase = "Pending"
	PaymentPhaseProcessing PaymentPhase = "Processing"
	PaymentPhaseCompleted  PaymentPhase = "Completed"
	PaymentPhaseFailed     PaymentPhase = "Failed"
)

var PaymentPhaseEnums = struct {
	Pending    PaymentPhase
	Processing PaymentPhase
	Completed  PaymentPhase
	Failed     PaymentPhase
}{
	Pending:    PaymentPhasePending,
	Processing: PaymentPhaseProcessing,
	Completed:  PaymentPhaseCompleted,
	Failed:     PaymentPhaseFailed,
}

// PaymentStage 阶段（Phase + Status）
type PaymentStage = PaymentPhase

// 预定义阶段
var (
	StagePaymentPending    = PaymentPhasePending
	StagePaymentProcessing = PaymentPhaseProcessing
	StagePaymentCompleted  = PaymentPhaseCompleted
	StagePaymentFailed     = PaymentPhaseFailed
)

// PaymentState 完整状态
type PaymentState struct {
	Current PaymentStage `json:"current"`
}

// PaymentStateColumns 数据库存储结构
type PaymentStateColumns struct {
	Phase PaymentPhase `gorm:"column:phase" json:"phase"`
}

func (s PaymentState) ToColumns() PaymentStateColumns {
	return PaymentStateColumns{
		Phase: s.Current,
	}
}

func (c PaymentStateColumns) ToState() PaymentState {
	return PaymentState{
		Current: c.Phase,
	}
}

// 错误定义
var ErrPaymentInvalidTransition = errors.New("invalid transition")

func (s PaymentState) TransitionTo(to PaymentStage) (PaymentState, error) {
	switch s.Current {
	case StagePaymentPending:
		switch to {
		case StagePaymentProcessing:
			return PaymentState{Current: to}, nil
		}
	case StagePaymentProcessing:
		switch to {
		case StagePaymentCompleted:
			return PaymentState{Current: to}, nil
		case StagePaymentFailed:
			return PaymentState{Current: to}, nil
		}
	case StagePaymentFailed:
		switch to {
		case StagePaymentProcessing:
			return PaymentState{Current: to}, nil
		}
	}
	return s, ErrPaymentInvalidTransition
}

func (s PaymentState) ValidTransitions() []PaymentStage {
	switch s.Current {
	case StagePaymentPending:
		return []PaymentStage{StagePaymentProcessing}
	case StagePaymentProcessing:
		return []PaymentStage{StagePaymentCompleted, StagePaymentFailed}
	case StagePaymentFailed:
		return []PaymentStage{StagePaymentProcessing}
	}
	return nil
}
