// Code generated by gogen. DO NOT EDIT.
package required_approval

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// DocumentPhase 阶段枚举
type DocumentPhase string

const (
	DocumentPhaseDraft     DocumentPhase = "Draft"
	DocumentPhasePublished DocumentPhase = "Published"
	DocumentPhaseReviewing DocumentPhase = "Reviewing"
	DocumentPhaseArchived  DocumentPhase = "Archived"
)

var DocumentPhaseEnums = struct {
	Draft     DocumentPhase
	Published DocumentPhase
	Reviewing DocumentPhase
	Archived  DocumentPhase
}{
	Draft:     DocumentPhaseDraft,
	Published: DocumentPhasePublished,
	Reviewing: DocumentPhaseReviewing,
	Archived:  DocumentPhaseArchived,
}

// DocumentStage 阶段（Phase + Status）
type DocumentStage = DocumentPhase

// 预定义阶段
var (
	StageDocumentDraft     = DocumentPhaseDraft
	StageDocumentPublished = DocumentPhasePublished
	StageDocumentReviewing = DocumentPhaseReviewing
	StageDocumentArchived  = DocumentPhaseArchived
)

// DocumentPendingTransition 审批事务
type DocumentPendingTransition struct {
	From     DocumentStage `json:"from"`
	To       DocumentStage `json:"to"`
	Fallback DocumentStage `json:"fallback"`
}

// DocumentState 完整状态
type DocumentState struct {
	Current DocumentStage              `json:"current"`
	Pending *DocumentPendingTransition `json:"pending,omitempty"`
}

// DocumentStateColumns 数据库存储结构
type DocumentStateColumns struct {
	Phase   DocumentPhase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*DocumentPendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s DocumentState) ToColumns() DocumentStateColumns {
	return DocumentStateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c DocumentStateColumns) ToState() DocumentState {
	return DocumentState{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrDocumentInvalidTransition  = errors.New("invalid transition")
	ErrDocumentApprovalInProgress = errors.New("approval in progress")
	ErrDocumentNotInApproval      = errors.New("not in approval")
)

func (s DocumentState) TransitionTo(to DocumentStage, withApproval bool) (DocumentState, error) {
	switch s.Current {
	case StageDocumentDraft:
		switch to {
		case StageDocumentPublished:
			if s.Pending != nil {
				return s, ErrDocumentApprovalInProgress
			}
			return DocumentState{Current: StageDocumentReviewing, Pending: &DocumentPendingTransition{From: s.Current, To: to, Fallback: StageDocumentDraft}}, nil
		}
	case StageDocumentPublished:
		switch to {
		case StageDocumentArchived:
			return DocumentState{Current: to}, nil
		}
	}
	return s, ErrDocumentInvalidTransition
}

func (s DocumentState) Commit() (DocumentState, error) {
	if s.Pending == nil {
		return s, ErrDocumentNotInApproval
	}
	return DocumentState{Current: s.Pending.To}, nil
}

func (s DocumentState) Reject() (DocumentState, error) {
	if s.Pending == nil {
		return s, ErrDocumentNotInApproval
	}
	return DocumentState{Current: s.Pending.Fallback}, nil
}

func (s DocumentState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s DocumentState) ValidTransitions() []DocumentStage {
	switch s.Current {
	case StageDocumentDraft:
		return []DocumentStage{StageDocumentPublished}
	case StageDocumentPublished:
		return []DocumentStage{StageDocumentArchived}
	}
	return nil
}
