// Code generated by gogen. DO NOT EDIT.
package self_transition

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// ConnectionPhase 阶段枚举
type ConnectionPhase string

const (
	ConnectionPhaseDisconnected ConnectionPhase = "Disconnected"
	ConnectionPhaseConnected    ConnectionPhase = "Connected"
	ConnectionPhaseReconnecting ConnectionPhase = "Reconnecting"
)

var ConnectionPhaseEnums = struct {
	Disconnected ConnectionPhase
	Connected    ConnectionPhase
	Reconnecting ConnectionPhase
}{
	Disconnected: ConnectionPhaseDisconnected,
	Connected:    ConnectionPhaseConnected,
	Reconnecting: ConnectionPhaseReconnecting,
}

// ConnectionStage 阶段（Phase + Status）
type ConnectionStage = ConnectionPhase

// 预定义阶段
var (
	StageConnectionDisconnected = ConnectionPhaseDisconnected
	StageConnectionConnected    = ConnectionPhaseConnected
	StageConnectionReconnecting = ConnectionPhaseReconnecting
)

// ConnectionPendingTransition 审批事务
type ConnectionPendingTransition struct {
	From     ConnectionStage `json:"from"`
	To       ConnectionStage `json:"to"`
	Fallback ConnectionStage `json:"fallback"`
}

// ConnectionState 完整状态
type ConnectionState struct {
	Current ConnectionStage              `json:"current"`
	Pending *ConnectionPendingTransition `json:"pending,omitempty"`
}

// ConnectionStateColumns 数据库存储结构
type ConnectionStateColumns struct {
	Phase   ConnectionPhase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*ConnectionPendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s ConnectionState) ToColumns() ConnectionStateColumns {
	return ConnectionStateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c ConnectionStateColumns) ToState() ConnectionState {
	return ConnectionState{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrConnectionInvalidTransition  = errors.New("invalid transition")
	ErrConnectionApprovalInProgress = errors.New("approval in progress")
	ErrConnectionNotInApproval      = errors.New("not in approval")
)

func (s ConnectionState) TransitionTo(to ConnectionStage, withApproval bool) (ConnectionState, error) {
	switch s.Current {
	case StageConnectionDisconnected:
		switch to {
		case StageConnectionConnected:
			return ConnectionState{Current: to}, nil
		}
	case StageConnectionConnected:
		switch to {
		case StageConnectionConnected:
			if withApproval {
				if s.Pending != nil {
					return s, ErrConnectionApprovalInProgress
				}
				return ConnectionState{Current: StageConnectionReconnecting, Pending: &ConnectionPendingTransition{From: s.Current, To: to, Fallback: StageConnectionConnected}}, nil
			}
			return ConnectionState{Current: to}, nil
		case StageConnectionDisconnected:
			return ConnectionState{Current: to}, nil
		}
	}
	return s, ErrConnectionInvalidTransition
}

func (s ConnectionState) Commit() (ConnectionState, error) {
	if s.Pending == nil {
		return s, ErrConnectionNotInApproval
	}
	return ConnectionState{Current: s.Pending.To}, nil
}

func (s ConnectionState) Reject() (ConnectionState, error) {
	if s.Pending == nil {
		return s, ErrConnectionNotInApproval
	}
	return ConnectionState{Current: s.Pending.Fallback}, nil
}

func (s ConnectionState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s ConnectionState) ValidTransitions() []ConnectionStage {
	switch s.Current {
	case StageConnectionDisconnected:
		return []ConnectionStage{StageConnectionConnected}
	case StageConnectionConnected:
		return []ConnectionStage{StageConnectionConnected, StageConnectionDisconnected}
	}
	return nil
}
