// Code generated by gogen. DO NOT EDIT.
package shared_via

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// ArticlePhase 阶段枚举
type ArticlePhase string

const (
	ArticlePhaseDraft     ArticlePhase = "Draft"
	ArticlePhasePublished ArticlePhase = "Published"
	ArticlePhaseReviewing ArticlePhase = "Reviewing"
	ArticlePhaseUpdated   ArticlePhase = "Updated"
	ArticlePhaseArchived  ArticlePhase = "Archived"
	ArticlePhaseDeleted   ArticlePhase = "Deleted"
)

var ArticlePhaseEnums = struct {
	Draft     ArticlePhase
	Published ArticlePhase
	Reviewing ArticlePhase
	Updated   ArticlePhase
	Archived  ArticlePhase
	Deleted   ArticlePhase
}{
	Draft:     ArticlePhaseDraft,
	Published: ArticlePhasePublished,
	Reviewing: ArticlePhaseReviewing,
	Updated:   ArticlePhaseUpdated,
	Archived:  ArticlePhaseArchived,
	Deleted:   ArticlePhaseDeleted,
}

// ArticleStage 阶段（Phase + Status）
type ArticleStage = ArticlePhase

// 预定义阶段
var (
	StageArticleDraft     = ArticlePhaseDraft
	StageArticlePublished = ArticlePhasePublished
	StageArticleReviewing = ArticlePhaseReviewing
	StageArticleUpdated   = ArticlePhaseUpdated
	StageArticleArchived  = ArticlePhaseArchived
	StageArticleDeleted   = ArticlePhaseDeleted
)

// ArticlePendingTransition 审批事务
type ArticlePendingTransition struct {
	From     ArticleStage `json:"from"`
	To       ArticleStage `json:"to"`
	Fallback ArticleStage `json:"fallback"`
}

// ArticleState 完整状态
type ArticleState struct {
	Current ArticleStage              `json:"current"`
	Pending *ArticlePendingTransition `json:"pending,omitempty"`
}

// ArticleStateColumns 数据库存储结构
type ArticleStateColumns struct {
	Phase   ArticlePhase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*ArticlePendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s ArticleState) ToColumns() ArticleStateColumns {
	return ArticleStateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c ArticleStateColumns) ToState() ArticleState {
	return ArticleState{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrArticleInvalidTransition  = errors.New("invalid transition")
	ErrArticleApprovalInProgress = errors.New("approval in progress")
	ErrArticleNotInApproval      = errors.New("not in approval")
)

func (s ArticleState) TransitionTo(to ArticleStage, withApproval bool) (ArticleState, error) {
	switch s.Current {
	case StageArticleDraft:
		switch to {
		case StageArticlePublished:
			if s.Pending != nil {
				return s, ErrArticleApprovalInProgress
			}
			return ArticleState{Current: StageArticleReviewing, Pending: &ArticlePendingTransition{From: s.Current, To: to, Fallback: StageArticleDraft}}, nil
		}
	case StageArticlePublished:
		switch to {
		case StageArticleUpdated:
			if s.Pending != nil {
				return s, ErrArticleApprovalInProgress
			}
			return ArticleState{Current: StageArticleReviewing, Pending: &ArticlePendingTransition{From: s.Current, To: to, Fallback: StageArticlePublished}}, nil
		}
	case StageArticleUpdated:
		switch to {
		case StageArticleArchived:
			if s.Pending != nil {
				return s, ErrArticleApprovalInProgress
			}
			return ArticleState{Current: StageArticleReviewing, Pending: &ArticlePendingTransition{From: s.Current, To: to, Fallback: StageArticleUpdated}}, nil
		}
	case StageArticleArchived:
		switch to {
		case StageArticleDeleted:
			return ArticleState{Current: to}, nil
		}
	}
	return s, ErrArticleInvalidTransition
}

func (s ArticleState) Commit() (ArticleState, error) {
	if s.Pending == nil {
		return s, ErrArticleNotInApproval
	}
	return ArticleState{Current: s.Pending.To}, nil
}

func (s ArticleState) Reject() (ArticleState, error) {
	if s.Pending == nil {
		return s, ErrArticleNotInApproval
	}
	return ArticleState{Current: s.Pending.Fallback}, nil
}

func (s ArticleState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s ArticleState) ValidTransitions() []ArticleStage {
	switch s.Current {
	case StageArticleDraft:
		return []ArticleStage{StageArticlePublished}
	case StageArticlePublished:
		return []ArticleStage{StageArticleUpdated}
	case StageArticleUpdated:
		return []ArticleStage{StageArticleArchived}
	case StageArticleArchived:
		return []ArticleStage{StageArticleDeleted}
	}
	return nil
}
