// Code generated by gogen. DO NOT EDIT.
package ddl_types

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type EventSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	StartTime gsql.DateTimeField[time.Time]
	EventDate gsql.DateField[time.Time]
	EventTime gsql.TimeField[time.Time]
	CreatedAt gsql.DateTimeField[time.Time]
	fieldType Event
	alias     string
	tableName string
}

func (t EventSchemaType) TableName() string {
	return t.tableName
}

func (t EventSchemaType) Alias() string {
	return t.alias
}

func (t *EventSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.StartTime = t.StartTime.WithTable(&tn)
	t.EventDate = t.EventDate.WithTable(&tn)
	t.EventTime = t.EventTime.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t EventSchemaType) As(alias string) EventSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t EventSchemaType) ModelType() *Event {
	return &t.fieldType
}

func (t EventSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t EventSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.StartTime,
		t.EventDate,
		t.EventTime,
		t.CreatedAt,
	}
}

func (t EventSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var EventSchema = EventSchemaType{
	tableName: "events",
	ID:        gsql.IntFieldOf[uint64]("events", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("events", "name"),
	StartTime: gsql.DateTimeFieldOf[time.Time]("events", "start_time"),
	EventDate: gsql.DateFieldOf[time.Time]("events", "event_date"),
	EventTime: gsql.TimeFieldOf[time.Time]("events", "event_time"),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("events", "created_at"),
	fieldType: Event{},
}

type ScheduleSchemaType struct {
	ID          gsql.IntField[uint64]
	Title       gsql.StringField[string]
	ScheduleDay gsql.DateField[time.Time]
	StartHour   gsql.TimeField[time.Time]
	EndHour     gsql.TimeField[time.Time]
	fieldType   Schedule
	alias       string
	tableName   string
}

func (t ScheduleSchemaType) TableName() string {
	return t.tableName
}

func (t ScheduleSchemaType) Alias() string {
	return t.alias
}

func (t *ScheduleSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Title = t.Title.WithTable(&tn)
	t.ScheduleDay = t.ScheduleDay.WithTable(&tn)
	t.StartHour = t.StartHour.WithTable(&tn)
	t.EndHour = t.EndHour.WithTable(&tn)
}

func (t ScheduleSchemaType) As(alias string) ScheduleSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ScheduleSchemaType) ModelType() *Schedule {
	return &t.fieldType
}

func (t ScheduleSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ScheduleSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Title,
		t.ScheduleDay,
		t.StartHour,
		t.EndHour,
	}
}

func (t ScheduleSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ScheduleSchema = ScheduleSchemaType{
	tableName:   "schedules",
	ID:          gsql.IntFieldOf[uint64]("schedules", "id", field.FlagPrimaryKey),
	Title:       gsql.StringFieldOf[string]("schedules", "title"),
	ScheduleDay: gsql.DateFieldOf[time.Time]("schedules", "schedule_day"),
	StartHour:   gsql.TimeFieldOf[time.Time]("schedules", "start_hour"),
	EndHour:     gsql.TimeFieldOf[time.Time]("schedules", "end_hour"),
	fieldType:   Schedule{},
}
