// Code generated by gogen. DO NOT EDIT.
package lowercase

import "errors"

// ================ stateflow ================

// TicketPhase 阶段枚举
type TicketPhase string

const (
	TicketPhaseOpen     TicketPhase = "open"
	TicketPhasePending  TicketPhase = "pending"
	TicketPhaseResolved TicketPhase = "resolved"
	TicketPhaseRejected TicketPhase = "rejected"
	TicketPhaseClosed   TicketPhase = "closed"
)

var TicketPhaseEnums = struct {
	Open     TicketPhase
	Pending  TicketPhase
	Resolved TicketPhase
	Rejected TicketPhase
	Closed   TicketPhase
}{
	Open:     TicketPhaseOpen,
	Pending:  TicketPhasePending,
	Resolved: TicketPhaseResolved,
	Rejected: TicketPhaseRejected,
	Closed:   TicketPhaseClosed,
}

// TicketStage 阶段（Phase + Status）
type TicketStage = TicketPhase

// 预定义阶段
var (
	StageTicketOpen     = TicketPhaseOpen
	StageTicketPending  = TicketPhasePending
	StageTicketResolved = TicketPhaseResolved
	StageTicketRejected = TicketPhaseRejected
	StageTicketClosed   = TicketPhaseClosed
)

// TicketState 完整状态
type TicketState struct {
	Current TicketStage `json:"current"`
}

// TicketStateColumns 数据库存储结构
type TicketStateColumns struct {
	Phase TicketPhase `gorm:"column:phase" json:"phase"`
}

func (s TicketState) ToColumns() TicketStateColumns {
	return TicketStateColumns{
		Phase: s.Current,
	}
}

func (c TicketStateColumns) ToState() TicketState {
	return TicketState{
		Current: c.Phase,
	}
}

// 错误定义
var ErrTicketInvalidTransition = errors.New("invalid transition")

func (s TicketState) TransitionTo(to TicketStage) (TicketState, error) {
	switch s.Current {
	case StageTicketOpen:
		switch to {
		case StageTicketPending:
			return TicketState{Current: to}, nil
		}
	case StageTicketPending:
		switch to {
		case StageTicketResolved:
			return TicketState{Current: to}, nil
		case StageTicketRejected:
			return TicketState{Current: to}, nil
		}
	case StageTicketResolved:
		switch to {
		case StageTicketClosed:
			return TicketState{Current: to}, nil
		}
	case StageTicketRejected:
		switch to {
		case StageTicketOpen:
			return TicketState{Current: to}, nil
		}
	}
	return s, ErrTicketInvalidTransition
}

func (s TicketState) ValidTransitions() []TicketStage {
	switch s.Current {
	case StageTicketOpen:
		return []TicketStage{StageTicketPending}
	case StageTicketPending:
		return []TicketStage{StageTicketResolved, StageTicketRejected}
	case StageTicketResolved:
		return []TicketStage{StageTicketClosed}
	case StageTicketRejected:
		return []TicketStage{StageTicketOpen}
	}
	return nil
}
