// Code generated by gogen. DO NOT EDIT.
package alias

import "time"

// ================ pickgen ================

// AccountBasic 从 AccountWithAlias Pick 生成
type AccountBasic struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	Name      string  `json:"name" gorm:"column:name;size:100"`
	Balance   float64 `json:"balance" gorm:"column:balance"`
}

// From 从 AccountWithAlias 复制字段值
func (t *AccountBasic) From(src *AccountWithAlias) {
	t.ID = src.ID
	t.CreatedAt = src.CreatedAt
	t.Name = src.Name
	t.Balance = src.Balance
}

// NewAccountBasic 从 AccountWithAlias 创建 AccountBasic
func NewAccountBasic(src *AccountWithAlias) AccountBasic {
	var result AccountBasic
	result.From(src)
	return result
}

// ================ omitgen ================

// TransactionPublic 从 Transaction Omit 生成
type TransactionPublic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	AccountID uint64    `json:"account_id" gorm:"column:account_id;index"`
	Amount    float64   `json:"amount" gorm:"column:amount"`
	Type      string    `json:"type" gorm:"column:type;size:20"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
}

// From 从 Transaction 复制字段值
func (t *TransactionPublic) From(src *Transaction) {
	t.ID = src.ID
	t.AccountID = src.AccountID
	t.Amount = src.Amount
	t.Type = src.Type
	t.CreatedAt = src.CreatedAt
}

// NewTransactionPublic 从 Transaction 创建 TransactionPublic
func NewTransactionPublic(src *Transaction) TransactionPublic {
	var result TransactionPublic
	result.From(src)
	return result
}
