// Code generated by gogen. DO NOT EDIT.
package nullable_types

import (
	"database/sql"
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type ProfileSchemaType struct {
	ID         gsql.IntField[uint64]
	UserID     gsql.IntField[uint64]
	Bio        gsql.StringField[sql.NullString]
	Website    gsql.StringField[sql.NullString]
	ViewCount  gsql.IntField[int64]
	Rating     gsql.FloatField[sql.NullFloat64]
	IsPublic   gsql.IntField[bool]
	IsVerified gsql.IntField[sql.NullBool]
	CreatedAt  gsql.DateTimeField[time.Time]
	UpdatedAt  gsql.DateTimeField[sql.NullTime]
	ExpiredAt  gsql.DateField[sql.NullTime]
	fieldType  Profile
	alias      string
	tableName  string
}

func (t ProfileSchemaType) TableName() string {
	return t.tableName
}

func (t ProfileSchemaType) Alias() string {
	return t.alias
}

func (t *ProfileSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
	t.Bio = t.Bio.WithTable(&tn)
	t.Website = t.Website.WithTable(&tn)
	t.ViewCount = t.ViewCount.WithTable(&tn)
	t.Rating = t.Rating.WithTable(&tn)
	t.IsPublic = t.IsPublic.WithTable(&tn)
	t.IsVerified = t.IsVerified.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.ExpiredAt = t.ExpiredAt.WithTable(&tn)
}

func (t ProfileSchemaType) As(alias string) ProfileSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProfileSchemaType) ModelType() *Profile {
	return &t.fieldType
}

func (t ProfileSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProfileSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.UserID,
		t.Bio,
		t.Website,
		t.ViewCount,
		t.Rating,
		t.IsPublic,
		t.IsVerified,
		t.CreatedAt,
		t.UpdatedAt,
		t.ExpiredAt,
	}
}

func (t ProfileSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProfileSchema = ProfileSchemaType{
	tableName:  "profiles",
	ID:         gsql.IntFieldOf[uint64]("profiles", "id", field.FlagPrimaryKey),
	UserID:     gsql.IntFieldOf[uint64]("profiles", "user_id", field.FlagIndex),
	Bio:        gsql.StringFieldOf[sql.NullString]("profiles", "bio"),
	Website:    gsql.StringFieldOf[sql.NullString]("profiles", "website"),
	ViewCount:  gsql.IntFieldOf[int64]("profiles", "view_count"),
	Rating:     gsql.FloatFieldOf[sql.NullFloat64]("profiles", "rating"),
	IsPublic:   gsql.IntFieldOf[bool]("profiles", "is_public"),
	IsVerified: gsql.IntFieldOf[sql.NullBool]("profiles", "is_verified"),
	CreatedAt:  gsql.DateTimeFieldOf[time.Time]("profiles", "created_at"),
	UpdatedAt:  gsql.DateTimeFieldOf[sql.NullTime]("profiles", "updated_at"),
	ExpiredAt:  gsql.DateFieldOf[sql.NullTime]("profiles", "expired_at"),
	fieldType:  Profile{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	Age       gsql.IntField[sql.NullInt32]
	Score     gsql.FloatField[sql.NullFloat64]
	IsVIP     gsql.IntField[sql.NullBool]
	Nickname  gsql.StringField[sql.NullString]
	LoginAt   gsql.DateTimeField[sql.NullTime]
	BirthDate gsql.DateField[sql.NullTime]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Age = t.Age.WithTable(&tn)
	t.Score = t.Score.WithTable(&tn)
	t.IsVIP = t.IsVIP.WithTable(&tn)
	t.Nickname = t.Nickname.WithTable(&tn)
	t.LoginAt = t.LoginAt.WithTable(&tn)
	t.BirthDate = t.BirthDate.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Age,
		t.Score,
		t.IsVIP,
		t.Nickname,
		t.LoginAt,
		t.BirthDate,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey),
	Age:       gsql.IntFieldOf[sql.NullInt32]("users", "age"),
	Score:     gsql.FloatFieldOf[sql.NullFloat64]("users", "score"),
	IsVIP:     gsql.IntFieldOf[sql.NullBool]("users", "is_vip"),
	Nickname:  gsql.StringFieldOf[sql.NullString]("users", "nickname"),
	LoginAt:   gsql.DateTimeFieldOf[sql.NullTime]("users", "login_at"),
	BirthDate: gsql.DateFieldOf[sql.NullTime]("users", "birth_date"),
	fieldType: User{},
}
