// Code generated by gogen. DO NOT EDIT.
package else_fallback

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

/* Flowchart:
                                              ┌── <COMMIT> ──▶ Production ──▶ Archived
                                              │
Development ──▶ Testing ──▶ Deploying (via) ──┤
                                              │
                                              └── <REJECT> ──▶ Rollback ──▶ Development 🔁
*/

// ReleasePhase 阶段枚举
type ReleasePhase string

const (
	ReleasePhaseDevelopment ReleasePhase = "Development"
	ReleasePhaseTesting     ReleasePhase = "Testing"
	ReleasePhaseProduction  ReleasePhase = "Production"
	ReleasePhaseDeploying   ReleasePhase = "Deploying"
	ReleasePhaseRollback    ReleasePhase = "Rollback"
	ReleasePhaseArchived    ReleasePhase = "Archived"
)

var ReleasePhaseEnums = struct {
	Development ReleasePhase
	Testing     ReleasePhase
	Production  ReleasePhase
	Deploying   ReleasePhase
	Rollback    ReleasePhase
	Archived    ReleasePhase
}{
	Development: ReleasePhaseDevelopment,
	Testing:     ReleasePhaseTesting,
	Production:  ReleasePhaseProduction,
	Deploying:   ReleasePhaseDeploying,
	Rollback:    ReleasePhaseRollback,
	Archived:    ReleasePhaseArchived,
}

// ReleaseStage 阶段（Phase + Status）
type ReleaseStage = ReleasePhase

// 预定义阶段
var (
	StageReleaseDevelopment = ReleasePhaseDevelopment
	StageReleaseTesting     = ReleasePhaseTesting
	StageReleaseProduction  = ReleasePhaseProduction
	StageReleaseDeploying   = ReleasePhaseDeploying
	StageReleaseRollback    = ReleasePhaseRollback
	StageReleaseArchived    = ReleasePhaseArchived
)

// ReleasePendingTransition 审批事务
type ReleasePendingTransition struct {
	From     ReleaseStage `json:"from"`
	To       ReleaseStage `json:"to"`
	Fallback ReleaseStage `json:"fallback"`
}

// ReleaseState 完整状态
type ReleaseState struct {
	Current ReleaseStage              `json:"current"`
	Pending *ReleasePendingTransition `json:"pending,omitempty"`
}

// ReleaseStateColumns 数据库存储结构
type ReleaseStateColumns struct {
	Phase   ReleasePhase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*ReleasePendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s ReleaseState) ToColumns() ReleaseStateColumns {
	return ReleaseStateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c ReleaseStateColumns) ToState() ReleaseState {
	return ReleaseState{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrReleaseInvalidTransition  = errors.New("invalid transition")
	ErrReleaseApprovalInProgress = errors.New("approval in progress")
	ErrReleaseNotInApproval      = errors.New("not in approval")
)

func (s ReleaseState) TransitionTo(to ReleaseStage) (ReleaseState, error) {
	switch s.Current {
	case StageReleaseDevelopment:
		switch to {
		case StageReleaseTesting:
			return ReleaseState{Current: to}, nil
		}
	case StageReleaseTesting:
		switch to {
		case StageReleaseProduction:
			if s.Pending != nil {
				return s, ErrReleaseApprovalInProgress
			}
			return ReleaseState{Current: StageReleaseDeploying, Pending: &ReleasePendingTransition{From: s.Current, To: to, Fallback: StageReleaseRollback}}, nil
		}
	case StageReleaseProduction:
		switch to {
		case StageReleaseArchived:
			return ReleaseState{Current: to}, nil
		}
	case StageReleaseRollback:
		switch to {
		case StageReleaseDevelopment:
			return ReleaseState{Current: to}, nil
		}
	}
	return s, ErrReleaseInvalidTransition
}

func (s ReleaseState) Commit() (ReleaseState, error) {
	if s.Pending == nil {
		return s, ErrReleaseNotInApproval
	}
	return ReleaseState{Current: s.Pending.To}, nil
}

func (s ReleaseState) Reject() (ReleaseState, error) {
	if s.Pending == nil {
		return s, ErrReleaseNotInApproval
	}
	return ReleaseState{Current: s.Pending.Fallback}, nil
}

func (s ReleaseState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s ReleaseState) ValidTransitions() []ReleaseStage {
	switch s.Current {
	case StageReleaseDevelopment:
		return []ReleaseStage{StageReleaseTesting}
	case StageReleaseTesting:
		return []ReleaseStage{StageReleaseProduction}
	case StageReleaseProduction:
		return []ReleaseStage{StageReleaseArchived}
	case StageReleaseRollback:
		return []ReleaseStage{StageReleaseDevelopment}
	}
	return nil
}

func (s ReleaseState) Next() []ReleaseState {
	if s.Pending != nil {
		return nil
	}
	var result []ReleaseState
	for _, stage := range s.ValidTransitions() {
		result = append(result, ReleaseState{Current: stage})
	}
	return result
}
