// Code generated by gogen. DO NOT EDIT.
package remote

import (
	"time"

	"github.com/donutnomad/gogen/pickgen/examples/basic"
	"gorm.io/gorm"
)

// ================ pickgen ================

// ExternalOrderSummary 从 Product Pick 生成
type ExternalOrderSummary struct {
	ID    uint64  `json:"id" gorm:"primaryKey"`
	Name  string  `json:"name" gorm:"column:name;size:200"`
	Price float64 `json:"price" gorm:"column:price"`
}

// From 从 basic.Product 复制字段值
func (t *ExternalOrderSummary) From(src *basic.Product) {
	t.ID = src.ID
	t.Name = src.Name
	t.Price = src.Price
}

// NewExternalOrderSummary 从 basic.Product 创建 ExternalOrderSummary
func NewExternalOrderSummary(src *basic.Product) ExternalOrderSummary {
	var result ExternalOrderSummary
	result.From(src)
	return result
}

// GormBasic 从 Model Pick 生成
type GormBasic struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

// From 从 gorm.Model 复制字段值
func (t *GormBasic) From(src *gorm.Model) {
	t.ID = src.ID
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewGormBasic 从 gorm.Model 创建 GormBasic
func NewGormBasic(src *gorm.Model) GormBasic {
	var result GormBasic
	result.From(src)
	return result
}

// UserFromBasic 从 User Pick 生成
type UserFromBasic struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Name  string `json:"name" gorm:"column:name;size:100"`
	Email string `json:"email" gorm:"column:email;uniqueIndex"`
}

// From 从 basic.User 复制字段值
func (t *UserFromBasic) From(src *basic.User) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
}

// NewUserFromBasic 从 basic.User 创建 UserFromBasic
func NewUserFromBasic(src *basic.User) UserFromBasic {
	var result UserFromBasic
	result.From(src)
	return result
}

// UserGormBasic 从 UserWithGorm Pick 生成
type UserGormBasic struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	Name      string `json:"name" gorm:"column:name;size:100"`
	Email     string `json:"email" gorm:"column:email;uniqueIndex"`
}

// From 从 UserWithGorm 复制字段值
func (t *UserGormBasic) From(src *UserWithGorm) {
	t.ID = src.ID
	t.CreatedAt = src.CreatedAt
	t.Name = src.Name
	t.Email = src.Email
}

// NewUserGormBasic 从 UserWithGorm 创建 UserGormBasic
func NewUserGormBasic(src *UserWithGorm) UserGormBasic {
	var result UserGormBasic
	result.From(src)
	return result
}

// ================ omitgen ================

// GormNoDelete 从 Model Omit 生成
type GormNoDelete struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

// From 从 gorm.Model 复制字段值
func (t *GormNoDelete) From(src *gorm.Model) {
	t.ID = src.ID
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewGormNoDelete 从 gorm.Model 创建 GormNoDelete
func NewGormNoDelete(src *gorm.Model) GormNoDelete {
	var result GormNoDelete
	result.From(src)
	return result
}
