// Code generated by gogen. DO NOT EDIT.
package examples

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// 流程图：
// ```
//                                                                                                                                         ┌──▶ Ready(Enabled) 🔁
//                                                                                                                                         │
//                                                               ┌── <COMMIT> ──▶ Ready(Disabled) ──▶ Deleting (via)── <COMMIT> ──▶ Deleted
//                                                               │                                                                         │
//                                                               │                                                                         └── <REJECT> ──▶ Ready(Disabled) 🔁
//                                                               │
//                                                               ├── <REJECT> ──▶ Ready(Enabled) 🔁
//                                                               │
//                         ┌──▶ Ready(Enabled) ──▶ Deleting (via)
//                         │                                     │
//                         │                                     ├── <COMMIT> ──▶ Deleted
//                         │                                     │
//                         │                                     └── <REJECT> ──▶ Ready(Enabled) 🔁
// Init ──▶ Provisioning ──┤
//                         │
//                         │
//                         │                             ┌── <COMMIT> ──▶ Deleted
//                         │                             │
//                         └──▶ Failed ──▶ Deleting (via)
//                                                       │
//                                                       └── <REJECT> ──▶ Failed 🔁
// ```

// ServerPhase 阶段枚举
type ServerPhase string

const (
	ServerPhaseInit         ServerPhase = "Init"
	ServerPhaseProvisioning ServerPhase = "Provisioning"
	ServerPhaseReady        ServerPhase = "Ready"
	ServerPhaseFailed       ServerPhase = "Failed"
	ServerPhaseUpdating     ServerPhase = "Updating"
	ServerPhaseDeleted      ServerPhase = "Deleted"
	ServerPhaseDeleting     ServerPhase = "Deleting"
)

var ServerPhaseEnums = struct {
	Init         ServerPhase
	Provisioning ServerPhase
	Ready        ServerPhase
	Failed       ServerPhase
	Updating     ServerPhase
	Deleted      ServerPhase
	Deleting     ServerPhase
}{
	Init:         ServerPhaseInit,
	Provisioning: ServerPhaseProvisioning,
	Ready:        ServerPhaseReady,
	Failed:       ServerPhaseFailed,
	Updating:     ServerPhaseUpdating,
	Deleted:      ServerPhaseDeleted,
	Deleting:     ServerPhaseDeleting,
}

// ServerStatus 状态枚举
type ServerStatus string

const (
	ServerStatusNone     ServerStatus = ""
	ServerStatusDisabled ServerStatus = "Disabled"
	ServerStatusEnabled  ServerStatus = "Enabled"
)

var ServerStatusEnums = struct {
	None     ServerStatus
	Disabled ServerStatus
	Enabled  ServerStatus
}{
	None:     ServerStatusNone,
	Disabled: ServerStatusDisabled,
	Enabled:  ServerStatusEnabled,
}

// ServerStage 阶段（Phase + Status）
type ServerStage struct {
	Phase  ServerPhase  `json:"phase"`
	Status ServerStatus `json:"status"`
}

// 预定义阶段
var (
	StageServerInit          = ServerStage{ServerPhaseInit, ServerStatusNone}
	StageServerProvisioning  = ServerStage{ServerPhaseProvisioning, ServerStatusNone}
	StageServerReadyDisabled = ServerStage{ServerPhaseReady, ServerStatusDisabled}
	StageServerReadyEnabled  = ServerStage{ServerPhaseReady, ServerStatusEnabled}
	StageServerFailed        = ServerStage{ServerPhaseFailed, ServerStatusNone}
	StageServerUpdating      = ServerStage{ServerPhaseUpdating, ServerStatusNone}
	StageServerDeleted       = ServerStage{ServerPhaseDeleted, ServerStatusNone}
	StageServerDeleting      = ServerStage{ServerPhaseDeleting, ServerStatusNone}
)

// ServerPendingTransition 审批事务
type ServerPendingTransition struct {
	From     ServerStage `json:"from"`
	To       ServerStage `json:"to"`
	Fallback ServerStage `json:"fallback"`
}

// ServerState 完整状态
type ServerState struct {
	Current ServerStage              `json:"current"`
	Pending *ServerPendingTransition `json:"pending,omitempty"`
}

// ServerStateColumns 数据库存储结构
type ServerStateColumns struct {
	Phase   ServerPhase                                  `gorm:"column:phase" json:"phase"`
	Status  ServerStatus                                 `gorm:"column:status" json:"status"`
	Pending datatypes.JSONType[*ServerPendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s ServerState) ToColumns() ServerStateColumns {
	return ServerStateColumns{
		Phase:   s.Current.Phase,
		Status:  s.Current.Status,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c ServerStateColumns) ToState() ServerState {
	return ServerState{
		Current: ServerStage{Phase: c.Phase, Status: c.Status},
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrServerInvalidTransition  = errors.New("invalid transition")
	ErrServerApprovalInProgress = errors.New("approval in progress")
	ErrServerNotInApproval      = errors.New("not in approval")
)

func (s ServerState) TransitionTo(to ServerStage, withApproval bool) (ServerState, error) {
	switch s.Current {
	case StageServerInit:
		switch to {
		case StageServerProvisioning:
			return ServerState{Current: to}, nil
		}
	case StageServerProvisioning:
		switch to {
		case StageServerReadyEnabled:
			return ServerState{Current: to}, nil
		case StageServerFailed:
			return ServerState{Current: to}, nil
		}
	case StageServerReadyDisabled:
		switch to {
		case StageServerReadyEnabled:
			return ServerState{Current: to}, nil
		case StageServerDeleted:
			if s.Pending != nil {
				return s, ErrServerApprovalInProgress
			}
			return ServerState{Current: StageServerDeleting, Pending: &ServerPendingTransition{From: s.Current, To: to, Fallback: StageServerReadyDisabled}}, nil
		}
	case StageServerReadyEnabled:
		switch to {
		case StageServerReadyDisabled:
			if s.Pending != nil {
				return s, ErrServerApprovalInProgress
			}
			return ServerState{Current: StageServerUpdating, Pending: &ServerPendingTransition{From: s.Current, To: to, Fallback: StageServerReadyEnabled}}, nil
		case StageServerDeleted:
			if s.Pending != nil {
				return s, ErrServerApprovalInProgress
			}
			return ServerState{Current: StageServerDeleting, Pending: &ServerPendingTransition{From: s.Current, To: to, Fallback: StageServerReadyEnabled}}, nil
		}
	case StageServerFailed:
		switch to {
		case StageServerDeleted:
			if s.Pending != nil {
				return s, ErrServerApprovalInProgress
			}
			return ServerState{Current: StageServerDeleting, Pending: &ServerPendingTransition{From: s.Current, To: to, Fallback: StageServerFailed}}, nil
		}
	}
	return s, ErrServerInvalidTransition
}

func (s ServerState) Commit() (ServerState, error) {
	if s.Pending == nil {
		return s, ErrServerNotInApproval
	}
	return ServerState{Current: s.Pending.To}, nil
}

func (s ServerState) Reject() (ServerState, error) {
	if s.Pending == nil {
		return s, ErrServerNotInApproval
	}
	return ServerState{Current: s.Pending.Fallback}, nil
}

func (s ServerState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s ServerState) ValidTransitions() []ServerStage {
	switch s.Current {
	case StageServerInit:
		return []ServerStage{StageServerProvisioning}
	case StageServerProvisioning:
		return []ServerStage{StageServerReadyEnabled, StageServerFailed}
	case StageServerReadyDisabled:
		return []ServerStage{StageServerReadyEnabled, StageServerDeleted}
	case StageServerReadyEnabled:
		return []ServerStage{StageServerReadyDisabled, StageServerDeleted}
	case StageServerFailed:
		return []ServerStage{StageServerDeleted}
	}
	return nil
}
