// Code generated by gogen. DO NOT EDIT.
package example

import (
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/spf13/cast"
)

// ================ swaggen ================

func NewUserAPIWrap(inner IUserAPI, handler IUserAPIHandler) *UserAPIWrap {
	return &UserAPIWrap{
		inner:   inner,
		handler: handler,
	}
}

type IUserAPIHandler interface {
	PreHandlers() []gin.HandlerFunc
}

type UserAPIWrap struct {
	inner   IUserAPI
	handler IUserAPIHandler
}

func (a *UserAPIWrap) bind(router gin.IRoutes, method, path string, preHandlers, innerHandlers []gin.HandlerFunc, f gin.HandlerFunc) {
	var basePath string
	if v, ok := router.(interface {
		BasePath() string
	}); ok {
		basePath = v.BasePath()
	}
	handlers := make([]gin.HandlerFunc, 0, len(preHandlers)+len(innerHandlers)+1)
	handlers = append(handlers, preHandlers...)
	handlers = append(handlers, innerHandlers...)
	handlers = append(handlers, f)
	router.Handle(method, strings.TrimPrefix(path, basePath), handlers...)
}

// GetUser
// @Summary 获取用户
// @Tags 用户管理
// @Produce json
// @Security Bearer
// @Param id path integer true "id"
// @Success 200 {object} UserResponse
// @Router /api/v1/user/{id} [get]
func (a *UserAPIWrap) GetUser(ctx *gin.Context) {
	id := cast.ToInt64(ctx.Param("id"))
	result, err := a.inner.GetUser(ctx, id)
	onGinResponse[UserResponse](ctx, result, err)
}

// CreateUser
// @Summary 创建用户
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security Bearer
// @Param req body CreateUserReq true "req"
// @Success 200 {object} UserResponse
// @Router /api/v1/user [post]
func (a *UserAPIWrap) CreateUser(ctx *gin.Context) {
	var req CreateUserReq
	if !onGinBind(ctx, &req, "JSON") {
		return
	}
	result, err := a.inner.CreateUser(ctx, req)
	onGinResponse[UserResponse](ctx, result, err)
}

// DeleteUser
// @Summary 删除用户
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security Bearer
// @Param id path integer true "id"
// @Success 200 {object} error
// @Router /api/v1/user/{id} [delete]
func (a *UserAPIWrap) DeleteUser(ctx *gin.Context) {
	id := cast.ToInt64(ctx.Param("id"))
	err := a.inner.DeleteUser(ctx, id)
	onGinResponse[string](ctx, "", err)
}

func (a *UserAPIWrap) BindGetUser(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "GET", "/api/v1/user/:id", preHandlers, handlers, a.GetUser)
}

func (a *UserAPIWrap) BindCreateUser(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "POST", "/api/v1/user", preHandlers, handlers, a.CreateUser)
}

func (a *UserAPIWrap) BindDeleteUser(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	var handlers []gin.HandlerFunc
	if a.handler != nil {
		handlers = append(handlers, a.handler.PreHandlers()...)
	}
	a.bind(router, "DELETE", "/api/v1/user/:id", preHandlers, handlers, a.DeleteUser)
}

func (a *UserAPIWrap) BindAll(router gin.IRoutes, preHandlers ...gin.HandlerFunc) {
	a.BindGetUser(router, preHandlers...)
	a.BindCreateUser(router, preHandlers...)
	a.BindDeleteUser(router, preHandlers...)
}
