// Code generated by gogen. DO NOT EDIT.
package multi_template

import (
	"fmt"
	"strings"
)

// ================ templategen ================

// OrderQuery provides query builder for orders
type OrderQuery struct {
	tableName string
	schema    string
	fields    []string
	where     []string
}

func NewOrderQuery() *OrderQuery {
	return &OrderQuery{
		tableName: "orders",
		schema:    "public",
		fields: []string{
			"id",
			"status",
			"total",
		},
	}
}

func (q *OrderQuery) Select(fields ...string) *OrderQuery {
	q.fields = fields
	return q
}

func (q *OrderQuery) Where(condition string) *OrderQuery {
	q.where = append(q.where, condition)
	return q
}

func (q *OrderQuery) Build() string {
	return fmt.Sprintf("SELECT %s FROM %s.%s",
		strings.Join(q.fields, ", "),
		q.schema,
		q.tableName,
	)
}

// ProductQuery provides query builder for products
type ProductQuery struct {
	tableName string
	schema    string
	fields    []string
	where     []string
}

func NewProductQuery() *ProductQuery {
	return &ProductQuery{
		tableName: "products",
		schema:    "public",
		fields:    []string{},
	}
}

func (q *ProductQuery) Select(fields ...string) *ProductQuery {
	q.fields = fields
	return q
}

func (q *ProductQuery) Where(condition string) *ProductQuery {
	q.where = append(q.where, condition)
	return q
}

func (q *ProductQuery) Build() string {
	return fmt.Sprintf("SELECT %s FROM %s.%s",
		strings.Join(q.fields, ", "),
		q.schema,
		q.tableName,
	)
}
