// Code generated by gogen. DO NOT EDIT.
package multi_template

// ================ templategen ================

// OrderModel provides model methods for orders
type OrderModel struct {
	*Order
}

func NewOrderModel() *OrderModel {
	return &OrderModel{
		Order: &Order{},
	}
}

func (m *OrderModel) TableName() string {
	return "public.orders"
}

// ProductModel provides model methods for products
type ProductModel struct {
	*Product
}

func NewProductModel() *ProductModel {
	return &ProductModel{
		Product: &Product{},
	}
}

func (m *ProductModel) TableName() string {
	return "public.products"
}
