// Code generated by gogen. DO NOT EDIT.
package optional_approval

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

/* Flowchart:
                                                              ┌── <COMMIT> ──▶ Approved ──▶ Done
                                                              │
                                       ┌──▶ Reviewing (via) ──┤
                                       │                      │
                                       │                      └── <REJECT> ──▶ Submitted 🔁
Draft ──▶ Submitted ──▶ <?APPROVAL?> ──┤
                                       │
                                       │
                                       └──▶ Approved ──▶ Done
*/

// TaskPhase 阶段枚举
type TaskPhase string

const (
	TaskPhaseDraft     TaskPhase = "Draft"
	TaskPhaseSubmitted TaskPhase = "Submitted"
	TaskPhaseApproved  TaskPhase = "Approved"
	TaskPhaseReviewing TaskPhase = "Reviewing"
	TaskPhaseDone      TaskPhase = "Done"
)

var TaskPhaseEnums = struct {
	Draft     TaskPhase
	Submitted TaskPhase
	Approved  TaskPhase
	Reviewing TaskPhase
	Done      TaskPhase
}{
	Draft:     TaskPhaseDraft,
	Submitted: TaskPhaseSubmitted,
	Approved:  TaskPhaseApproved,
	Reviewing: TaskPhaseReviewing,
	Done:      TaskPhaseDone,
}

// TaskStage 阶段（Phase + Status）
type TaskStage = TaskPhase

// 预定义阶段
var (
	StageTaskDraft     = TaskPhaseDraft
	StageTaskSubmitted = TaskPhaseSubmitted
	StageTaskApproved  = TaskPhaseApproved
	StageTaskReviewing = TaskPhaseReviewing
	StageTaskDone      = TaskPhaseDone
)

// TaskPendingTransition 审批事务
type TaskPendingTransition struct {
	From     TaskStage `json:"from"`
	To       TaskStage `json:"to"`
	Fallback TaskStage `json:"fallback"`
}

// TaskState 完整状态
type TaskState struct {
	Current TaskStage              `json:"current"`
	Pending *TaskPendingTransition `json:"pending,omitempty"`
}

// TaskStateColumns 数据库存储结构
type TaskStateColumns struct {
	Phase   TaskPhase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*TaskPendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s TaskState) ToColumns() TaskStateColumns {
	return TaskStateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c TaskStateColumns) ToState() TaskState {
	return TaskState{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrTaskInvalidTransition  = errors.New("invalid transition")
	ErrTaskApprovalInProgress = errors.New("approval in progress")
	ErrTaskNotInApproval      = errors.New("not in approval")
)

func (s TaskState) TransitionTo(to TaskStage, withApproval bool) (TaskState, error) {
	switch s.Current {
	case StageTaskDraft:
		switch to {
		case StageTaskSubmitted:
			return TaskState{Current: to}, nil
		}
	case StageTaskSubmitted:
		switch to {
		case StageTaskApproved:
			if withApproval {
				if s.Pending != nil {
					return s, ErrTaskApprovalInProgress
				}
				return TaskState{Current: StageTaskReviewing, Pending: &TaskPendingTransition{From: s.Current, To: to, Fallback: StageTaskSubmitted}}, nil
			}
			return TaskState{Current: to}, nil
		}
	case StageTaskApproved:
		switch to {
		case StageTaskDone:
			return TaskState{Current: to}, nil
		}
	}
	return s, ErrTaskInvalidTransition
}

func (s TaskState) Commit() (TaskState, error) {
	if s.Pending == nil {
		return s, ErrTaskNotInApproval
	}
	return TaskState{Current: s.Pending.To}, nil
}

func (s TaskState) Reject() (TaskState, error) {
	if s.Pending == nil {
		return s, ErrTaskNotInApproval
	}
	return TaskState{Current: s.Pending.Fallback}, nil
}

func (s TaskState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s TaskState) ValidTransitions() []TaskStage {
	switch s.Current {
	case StageTaskDraft:
		return []TaskStage{StageTaskSubmitted}
	case StageTaskSubmitted:
		return []TaskStage{StageTaskApproved}
	case StageTaskApproved:
		return []TaskStage{StageTaskDone}
	}
	return nil
}

func (s TaskState) Next() []TaskState {
	if s.Pending != nil {
		return nil
	}
	var result []TaskState
	for _, stage := range s.ValidTransitions() {
		result = append(result, TaskState{Current: stage})
	}
	return result
}
