// Code generated by gogen. DO NOT EDIT.
package import_alias

import "context"

// ================ templategen ================

// Entity wrapper methods
// CreateWithContext wraps Create with additional context
// Operation: create
func (e *Entity) CreateWithContext(ctx context.Context) error {
	// Pre-create validation
	return e.Create(ctx)
}

// DeleteWithContext wraps Delete with additional context
// Operation: delete
func (e *Entity) DeleteWithContext(ctx context.Context, id string) error {
	// Pre-delete confirmation
	return e.Delete(ctx, id)
}
