package deep

//go:generate go run github.com/donutnomad/gogen gen ./...

// @StateFlow(output=types_state.go)
// @Flow: Start => [ L1 ]
// @Flow: L1 => [ L2A, L2B ]
// @Flow: L2A => [ L3A? via L2A_Review ]
// @Flow: L2B => [ L3B, L3C ]
// @Flow: L3A => [ L4A, L4B ]
// @Flow: L3B => [ L4C? via L3B_Review ]
// @Flow: L3C => [ L4D ]
// @Flow: L4A => [ L5A ]
// @Flow: L4B => [ L5B ]
// @Flow: L4C => [ L5C ]
// @Flow: L4D => [ L5D ]
// @Flow: L5A => [ L6A ]
// @Flow: L5B => [ L6B ]
// @Flow: L5C => [ L6C ]
// @Flow: L5D => [ L6D ]
// @Flow: L6A => [ L7A, L7B ]
// @Flow: L6B => [ L7C? via L6B_Review ]
// @Flow: L6C => [ L7D ]
// @Flow: L6D => [ L7E ]
// @Flow: L7A => [ L8A ]
// @Flow: L7B => [ L8B ]
// @Flow: L7C => [ L8C ]
// @Flow: L7D => [ L8D ]
// @Flow: L7E => [ L8E ]
// @Flow: L8A => [ L9A ]
// @Flow: L8B => [ L9B ]
// @Flow: L8C => [ L9C ]
// @Flow: L8D => [ L9D ]
// @Flow: L8E => [ L9E ]
// @Flow: L9A => [ End ]
// @Flow: L9B => [ End ]
// @Flow: L9C => [ End ]
// @Flow: L9D => [ End ]
// @Flow: L9E => [ End ]
const _ = ""
