// Code generated by gogen. DO NOT EDIT.
package deep

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// 流程图：
// ```
//                                                                                                                      ┌──▶ L7A ──▶ L8A ──▶ L9A ──▶ End
//                                                                                                                      │
//                                                                                           ┌──▶ L4A ──▶ L5A ──▶ L6A ──┤
//                                                                                           │                          │
//                                                                                           │                          └──▶ L7B ──▶ L8B ──▶ L9B ──▶ End
//                                                                                           │
//                                                                                           │
//                                                                                           │
//                                                                    ┌── <COMMIT> ──▶ L3A ──┤
//                                                                    │                      │                                                                   ┌── <COMMIT> ──▶ L7C ──▶ L8C ──▶ L9C ──▶ End
//                                                                    │                      │                                                                   │
//                                                                    │                      │                                           ┌──▶ L6B_Review (via) ──┤
//                                                                    │                      │                                           │                       │
//                                                                    │                      │                                           │                       └── <REJECT> ──▶ L6B 🔁
//                                                                    │                      └──▶ L4B ──▶ L5B ──▶ L6B ──▶ <?APPROVAL?> ──┤
//                                                                    │                                                                  │
//                                                                    │                                                                  │
//                                                                    │                                                                  └──▶ L7C ──▶ L8C ──▶ L9C ──▶ End
//                                            ┌──▶ L2A_Review (via) ──┤
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       │
//                                            │                       └── <REJECT> ──▶ L2A 🔁
//                ┌──▶ L2A ──▶ <?APPROVAL?> ──┤
//                │                           │
//                │                           │
//                │                           │                                     ┌──▶ L7A ──▶ L8A ──▶ L9A ──▶ End
//                │                           │                                     │
//                │                           │          ┌──▶ L4A ──▶ L5A ──▶ L6A ──┤
//                │                           │          │                          │
//                │                           │          │                          └──▶ L7B ──▶ L8B ──▶ L9B ──▶ End
//                │                           │          │
//                │                           │          │
//                │                           │          │
//                │                           └──▶ L3A ──┤
//                │                                      │                                                                   ┌── <COMMIT> ──▶ L7C ──▶ L8C ──▶ L9C ──▶ End
//                │                                      │                                                                   │
//                │                                      │                                           ┌──▶ L6B_Review (via) ──┤
//                │                                      │                                           │                       │
//                │                                      │                                           │                       └── <REJECT> ──▶ L6B 🔁
//                │                                      └──▶ L4B ──▶ L5B ──▶ L6B ──▶ <?APPROVAL?> ──┤
//                │                                                                                  │
//                │                                                                                  │
//                │                                                                                  └──▶ L7C ──▶ L8C ──▶ L9C ──▶ End
// Start ──▶ L1 ──┤
//                │
//                │
//                │
//                │
//                │
//                │
//                │
//                │
//                │
//                │
//                │
//                │                                                              ┌── <COMMIT> ──▶ L4C ──▶ L5C ──▶ L6C ──▶ L7D ──▶ L8D ──▶ L9D ──▶ End
//                │                                                              │
//                │                                      ┌──▶ L3B_Review (via) ──┤
//                │                                      │                       │
//                │                                      │                       └── <REJECT> ──▶ L3B 🔁
//                │          ┌──▶ L3B ──▶ <?APPROVAL?> ──┤
//                │          │                           │
//                │          │                           │
//                │          │                           └──▶ L4C ──▶ L5C ──▶ L6C ──▶ L7D ──▶ L8D ──▶ L9D ──▶ End
//                └──▶ L2B ──┤
//                           │
//                           │
//                           │
//                           └──▶ L3C ──▶ L4D ──▶ L5D ──▶ L6D ──▶ L7E ──▶ L8E ──▶ L9E ──▶ End
// ```

// Phase 阶段枚举
type Phase string

const (
	PhaseStart     Phase = "Start"
	PhaseL1        Phase = "L1"
	PhaseL2A       Phase = "L2A"
	PhaseL2B       Phase = "L2B"
	PhaseL3A       Phase = "L3A"
	PhaseL2AReview Phase = "L2A_Review"
	PhaseL3B       Phase = "L3B"
	PhaseL3C       Phase = "L3C"
	PhaseL4A       Phase = "L4A"
	PhaseL4B       Phase = "L4B"
	PhaseL4C       Phase = "L4C"
	PhaseL3BReview Phase = "L3B_Review"
	PhaseL4D       Phase = "L4D"
	PhaseL5A       Phase = "L5A"
	PhaseL5B       Phase = "L5B"
	PhaseL5C       Phase = "L5C"
	PhaseL5D       Phase = "L5D"
	PhaseL6A       Phase = "L6A"
	PhaseL6B       Phase = "L6B"
	PhaseL6C       Phase = "L6C"
	PhaseL6D       Phase = "L6D"
	PhaseL7A       Phase = "L7A"
	PhaseL7B       Phase = "L7B"
	PhaseL7C       Phase = "L7C"
	PhaseL6BReview Phase = "L6B_Review"
	PhaseL7D       Phase = "L7D"
	PhaseL7E       Phase = "L7E"
	PhaseL8A       Phase = "L8A"
	PhaseL8B       Phase = "L8B"
	PhaseL8C       Phase = "L8C"
	PhaseL8D       Phase = "L8D"
	PhaseL8E       Phase = "L8E"
	PhaseL9A       Phase = "L9A"
	PhaseL9B       Phase = "L9B"
	PhaseL9C       Phase = "L9C"
	PhaseL9D       Phase = "L9D"
	PhaseL9E       Phase = "L9E"
	PhaseEnd       Phase = "End"
)

var PhaseEnums = struct {
	Start     Phase
	L1        Phase
	L2A       Phase
	L2B       Phase
	L3A       Phase
	L2AReview Phase
	L3B       Phase
	L3C       Phase
	L4A       Phase
	L4B       Phase
	L4C       Phase
	L3BReview Phase
	L4D       Phase
	L5A       Phase
	L5B       Phase
	L5C       Phase
	L5D       Phase
	L6A       Phase
	L6B       Phase
	L6C       Phase
	L6D       Phase
	L7A       Phase
	L7B       Phase
	L7C       Phase
	L6BReview Phase
	L7D       Phase
	L7E       Phase
	L8A       Phase
	L8B       Phase
	L8C       Phase
	L8D       Phase
	L8E       Phase
	L9A       Phase
	L9B       Phase
	L9C       Phase
	L9D       Phase
	L9E       Phase
	End       Phase
}{
	Start:     PhaseStart,
	L1:        PhaseL1,
	L2A:       PhaseL2A,
	L2B:       PhaseL2B,
	L3A:       PhaseL3A,
	L2AReview: PhaseL2AReview,
	L3B:       PhaseL3B,
	L3C:       PhaseL3C,
	L4A:       PhaseL4A,
	L4B:       PhaseL4B,
	L4C:       PhaseL4C,
	L3BReview: PhaseL3BReview,
	L4D:       PhaseL4D,
	L5A:       PhaseL5A,
	L5B:       PhaseL5B,
	L5C:       PhaseL5C,
	L5D:       PhaseL5D,
	L6A:       PhaseL6A,
	L6B:       PhaseL6B,
	L6C:       PhaseL6C,
	L6D:       PhaseL6D,
	L7A:       PhaseL7A,
	L7B:       PhaseL7B,
	L7C:       PhaseL7C,
	L6BReview: PhaseL6BReview,
	L7D:       PhaseL7D,
	L7E:       PhaseL7E,
	L8A:       PhaseL8A,
	L8B:       PhaseL8B,
	L8C:       PhaseL8C,
	L8D:       PhaseL8D,
	L8E:       PhaseL8E,
	L9A:       PhaseL9A,
	L9B:       PhaseL9B,
	L9C:       PhaseL9C,
	L9D:       PhaseL9D,
	L9E:       PhaseL9E,
	End:       PhaseEnd,
}

// Stage 阶段（Phase + Status）
type Stage = Phase

// 预定义阶段
var (
	StageStart     = PhaseStart
	StageL1        = PhaseL1
	StageL2A       = PhaseL2A
	StageL2B       = PhaseL2B
	StageL3A       = PhaseL3A
	StageL2AReview = PhaseL2AReview
	StageL3B       = PhaseL3B
	StageL3C       = PhaseL3C
	StageL4A       = PhaseL4A
	StageL4B       = PhaseL4B
	StageL4C       = PhaseL4C
	StageL3BReview = PhaseL3BReview
	StageL4D       = PhaseL4D
	StageL5A       = PhaseL5A
	StageL5B       = PhaseL5B
	StageL5C       = PhaseL5C
	StageL5D       = PhaseL5D
	StageL6A       = PhaseL6A
	StageL6B       = PhaseL6B
	StageL6C       = PhaseL6C
	StageL6D       = PhaseL6D
	StageL7A       = PhaseL7A
	StageL7B       = PhaseL7B
	StageL7C       = PhaseL7C
	StageL6BReview = PhaseL6BReview
	StageL7D       = PhaseL7D
	StageL7E       = PhaseL7E
	StageL8A       = PhaseL8A
	StageL8B       = PhaseL8B
	StageL8C       = PhaseL8C
	StageL8D       = PhaseL8D
	StageL8E       = PhaseL8E
	StageL9A       = PhaseL9A
	StageL9B       = PhaseL9B
	StageL9C       = PhaseL9C
	StageL9D       = PhaseL9D
	StageL9E       = PhaseL9E
	StageEnd       = PhaseEnd
)

// PendingTransition 审批事务
type PendingTransition struct {
	From     Stage `json:"from"`
	To       Stage `json:"to"`
	Fallback Stage `json:"fallback"`
}

// State 完整状态
type State struct {
	Current Stage              `json:"current"`
	Pending *PendingTransition `json:"pending,omitempty"`
}

// StateColumns 数据库存储结构
type StateColumns struct {
	Phase   Phase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*PendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s State) ToColumns() StateColumns {
	return StateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c StateColumns) ToState() State {
	return State{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrInvalidTransition  = errors.New("invalid transition")
	ErrApprovalInProgress = errors.New("approval in progress")
	ErrNotInApproval      = errors.New("not in approval")
)

func (s State) TransitionTo(to Stage, withApproval bool) (State, error) {
	switch s.Current {
	case StageStart:
		switch to {
		case StageL1:
			return State{Current: to}, nil
		}
	case StageL1:
		switch to {
		case StageL2A:
			return State{Current: to}, nil
		case StageL2B:
			return State{Current: to}, nil
		}
	case StageL2A:
		switch to {
		case StageL3A:
			if withApproval {
				if s.Pending != nil {
					return s, ErrApprovalInProgress
				}
				return State{Current: StageL2AReview, Pending: &PendingTransition{From: s.Current, To: to, Fallback: StageL2A}}, nil
			}
			return State{Current: to}, nil
		}
	case StageL2B:
		switch to {
		case StageL3B:
			return State{Current: to}, nil
		case StageL3C:
			return State{Current: to}, nil
		}
	case StageL3A:
		switch to {
		case StageL4A:
			return State{Current: to}, nil
		case StageL4B:
			return State{Current: to}, nil
		}
	case StageL3B:
		switch to {
		case StageL4C:
			if withApproval {
				if s.Pending != nil {
					return s, ErrApprovalInProgress
				}
				return State{Current: StageL3BReview, Pending: &PendingTransition{From: s.Current, To: to, Fallback: StageL3B}}, nil
			}
			return State{Current: to}, nil
		}
	case StageL3C:
		switch to {
		case StageL4D:
			return State{Current: to}, nil
		}
	case StageL4A:
		switch to {
		case StageL5A:
			return State{Current: to}, nil
		}
	case StageL4B:
		switch to {
		case StageL5B:
			return State{Current: to}, nil
		}
	case StageL4C:
		switch to {
		case StageL5C:
			return State{Current: to}, nil
		}
	case StageL4D:
		switch to {
		case StageL5D:
			return State{Current: to}, nil
		}
	case StageL5A:
		switch to {
		case StageL6A:
			return State{Current: to}, nil
		}
	case StageL5B:
		switch to {
		case StageL6B:
			return State{Current: to}, nil
		}
	case StageL5C:
		switch to {
		case StageL6C:
			return State{Current: to}, nil
		}
	case StageL5D:
		switch to {
		case StageL6D:
			return State{Current: to}, nil
		}
	case StageL6A:
		switch to {
		case StageL7A:
			return State{Current: to}, nil
		case StageL7B:
			return State{Current: to}, nil
		}
	case StageL6B:
		switch to {
		case StageL7C:
			if withApproval {
				if s.Pending != nil {
					return s, ErrApprovalInProgress
				}
				return State{Current: StageL6BReview, Pending: &PendingTransition{From: s.Current, To: to, Fallback: StageL6B}}, nil
			}
			return State{Current: to}, nil
		}
	case StageL6C:
		switch to {
		case StageL7D:
			return State{Current: to}, nil
		}
	case StageL6D:
		switch to {
		case StageL7E:
			return State{Current: to}, nil
		}
	case StageL7A:
		switch to {
		case StageL8A:
			return State{Current: to}, nil
		}
	case StageL7B:
		switch to {
		case StageL8B:
			return State{Current: to}, nil
		}
	case StageL7C:
		switch to {
		case StageL8C:
			return State{Current: to}, nil
		}
	case StageL7D:
		switch to {
		case StageL8D:
			return State{Current: to}, nil
		}
	case StageL7E:
		switch to {
		case StageL8E:
			return State{Current: to}, nil
		}
	case StageL8A:
		switch to {
		case StageL9A:
			return State{Current: to}, nil
		}
	case StageL8B:
		switch to {
		case StageL9B:
			return State{Current: to}, nil
		}
	case StageL8C:
		switch to {
		case StageL9C:
			return State{Current: to}, nil
		}
	case StageL8D:
		switch to {
		case StageL9D:
			return State{Current: to}, nil
		}
	case StageL8E:
		switch to {
		case StageL9E:
			return State{Current: to}, nil
		}
	case StageL9A:
		switch to {
		case StageEnd:
			return State{Current: to}, nil
		}
	case StageL9B:
		switch to {
		case StageEnd:
			return State{Current: to}, nil
		}
	case StageL9C:
		switch to {
		case StageEnd:
			return State{Current: to}, nil
		}
	case StageL9D:
		switch to {
		case StageEnd:
			return State{Current: to}, nil
		}
	case StageL9E:
		switch to {
		case StageEnd:
			return State{Current: to}, nil
		}
	}
	return s, ErrInvalidTransition
}

func (s State) Commit() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.To}, nil
}

func (s State) Reject() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.Fallback}, nil
}

func (s State) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s State) ValidTransitions() []Stage {
	switch s.Current {
	case StageStart:
		return []Stage{StageL1}
	case StageL1:
		return []Stage{StageL2A, StageL2B}
	case StageL2A:
		return []Stage{StageL3A}
	case StageL2B:
		return []Stage{StageL3B, StageL3C}
	case StageL3A:
		return []Stage{StageL4A, StageL4B}
	case StageL3B:
		return []Stage{StageL4C}
	case StageL3C:
		return []Stage{StageL4D}
	case StageL4A:
		return []Stage{StageL5A}
	case StageL4B:
		return []Stage{StageL5B}
	case StageL4C:
		return []Stage{StageL5C}
	case StageL4D:
		return []Stage{StageL5D}
	case StageL5A:
		return []Stage{StageL6A}
	case StageL5B:
		return []Stage{StageL6B}
	case StageL5C:
		return []Stage{StageL6C}
	case StageL5D:
		return []Stage{StageL6D}
	case StageL6A:
		return []Stage{StageL7A, StageL7B}
	case StageL6B:
		return []Stage{StageL7C}
	case StageL6C:
		return []Stage{StageL7D}
	case StageL6D:
		return []Stage{StageL7E}
	case StageL7A:
		return []Stage{StageL8A}
	case StageL7B:
		return []Stage{StageL8B}
	case StageL7C:
		return []Stage{StageL8C}
	case StageL7D:
		return []Stage{StageL8D}
	case StageL7E:
		return []Stage{StageL8E}
	case StageL8A:
		return []Stage{StageL9A}
	case StageL8B:
		return []Stage{StageL9B}
	case StageL8C:
		return []Stage{StageL9C}
	case StageL8D:
		return []Stage{StageL9D}
	case StageL8E:
		return []Stage{StageL9E}
	case StageL9A:
		return []Stage{StageEnd}
	case StageL9B:
		return []Stage{StageEnd}
	case StageL9C:
		return []Stage{StageEnd}
	case StageL9D:
		return []Stage{StageEnd}
	case StageL9E:
		return []Stage{StageEnd}
	}
	return nil
}

func (s State) Next() []State {
	if s.Pending != nil {
		return nil
	}
	var result []State
	for _, stage := range s.ValidTransitions() {
		result = append(result, State{Current: stage})
	}
	return result
}
