// Code generated by gogen. DO NOT EDIT.
package embedded

import "time"

// ================ pickgen ================

// CustomerBasic 从 Customer Pick 生成
type CustomerBasic struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Name  string `json:"name" gorm:"column:name;size:100"`
	Email string `json:"email" gorm:"column:email;uniqueIndex"`
}

// From 从 Customer 复制字段值
func (t *CustomerBasic) From(src *Customer) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
}

// NewCustomerBasic 从 Customer 创建 CustomerBasic
func NewCustomerBasic(src *Customer) CustomerBasic {
	var result CustomerBasic
	result.From(src)
	return result
}

// EmployeeBasic 从 Employee Pick 生成
type EmployeeBasic struct {
	ID         uint64 `json:"id" gorm:"primaryKey"`
	Name       string `json:"name" gorm:"column:name;size:100"`
	Email      string `json:"email" gorm:"column:email;uniqueIndex"`
	Department string `json:"department" gorm:"column:department;size:50"`
}

// From 从 Employee 复制字段值
func (t *EmployeeBasic) From(src *Employee) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.Department = src.Department
}

// NewEmployeeBasic 从 Employee 创建 EmployeeBasic
func NewEmployeeBasic(src *Employee) EmployeeBasic {
	var result EmployeeBasic
	result.From(src)
	return result
}

// OrderSummary 从 Order Pick 生成
type OrderSummary struct {
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	ID        uint64    `json:"id" gorm:"primaryKey"`
	OrderNo   string    `json:"order_no" gorm:"column:order_no;uniqueIndex"`
	Total     float64   `json:"total" gorm:"column:total"`
	Status    string    `json:"status" gorm:"column:status;size:20"`
}

// From 从 Order 复制字段值
func (t *OrderSummary) From(src *Order) {
	t.CreatedAt = src.CreatedAt
	t.ID = src.ID
	t.OrderNo = src.OrderNo
	t.Total = src.Total
	t.Status = src.Status
}

// NewOrderSummary 从 Order 创建 OrderSummary
func NewOrderSummary(src *Order) OrderSummary {
	var result OrderSummary
	result.From(src)
	return result
}

// ================ omitgen ================

// EmployeePublic 从 Employee Omit 生成
type EmployeePublic struct {
	ID         uint64    `json:"id" gorm:"primaryKey"`
	CreatedAt  time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt  time.Time `json:"updated_at" gorm:"autoUpdateTime"`
	Name       string    `json:"name" gorm:"column:name;size:100"`
	Email      string    `json:"email" gorm:"column:email;uniqueIndex"`
	Department string    `json:"department" gorm:"column:department;size:50"`
}

// From 从 Employee 复制字段值
func (t *EmployeePublic) From(src *Employee) {
	t.ID = src.ID
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
	t.Name = src.Name
	t.Email = src.Email
	t.Department = src.Department
}

// NewEmployeePublic 从 Employee 创建 EmployeePublic
func NewEmployeePublic(src *Employee) EmployeePublic {
	var result EmployeePublic
	result.From(src)
	return result
}

// OrderList 从 Order Omit 生成
type OrderList struct {
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	ID        uint64    `json:"id" gorm:"primaryKey"`
	OrderNo   string    `json:"order_no" gorm:"column:order_no;uniqueIndex"`
	UserID    uint64    `json:"user_id" gorm:"column:user_id;index"`
	Total     float64   `json:"total" gorm:"column:total"`
	Status    string    `json:"status" gorm:"column:status;size:20"`
}

// From 从 Order 复制字段值
func (t *OrderList) From(src *Order) {
	t.CreatedAt = src.CreatedAt
	t.ID = src.ID
	t.OrderNo = src.OrderNo
	t.UserID = src.UserID
	t.Total = src.Total
	t.Status = src.Status
}

// NewOrderList 从 Order 创建 OrderList
func NewOrderList(src *Order) OrderList {
	var result OrderList
	result.From(src)
	return result
}
