// Code generated by gogen. DO NOT EDIT.
package template_inheritance

import (
	"context"
	"log"
)

// ================ templategen ================

// Auto-generated CRUD operations
// Table: customers
// Soft Delete: true

// CreateWithLog wraps Create with logging
// Action: create
func (c *Customer) CreateWithLog(ctx context.Context) error {
	log.Printf("[CREATE] Customer.Create called")
	defer log.Printf("[CREATE] Customer.Create completed")
	return c.Create(ctx)
}

// ReadWithLog wraps Read with logging
// Action: read
func (c *Customer) ReadWithLog(ctx context.Context, id int64) error {
	log.Printf("[READ] Customer.Read called")
	defer log.Printf("[READ] Customer.Read completed")
	return c.Read(ctx, id)
}

// UpdateWithLog wraps Update with logging
// Action: update
func (c *Customer) UpdateWithLog(ctx context.Context) error {
	log.Printf("[UPDATE] Customer.Update called")
	defer log.Printf("[UPDATE] Customer.Update completed")
	return c.Update(ctx)
}

// DeleteWithLog wraps Delete with logging
// Action: delete
func (c *Customer) DeleteWithLog(ctx context.Context, id int64) error {
	log.Printf("[DELETE] Customer.Delete called")
	defer log.Printf("[DELETE] Customer.Delete completed")
	return c.Delete(ctx, id)
}
