// Code generated by gogen. DO NOT EDIT.
package mixed

import (
	"errors"

	"google.golang.org/grpc/codes"
)

// ================ codegen ================

// GetHttpCode 返回错误对应的HTTP状态码
func GetHttpCode[T comparable](v T) (int, bool) {
	switch val := any(v).(type) {
	case error:
		if errors.Is(val, ErrMixed1) {
			return 404, true
		}
		if errors.Is(val, ErrMixed2) {
			return 500, true
		}
	default:
		if any(val) == any(CodeInt) {
			return 200, true
		}
		if any(val) == any(CodeInt32) {
			return 201, true
		}
		if any(val) == any(CodeInt64) {
			return 400, true
		}
		if any(val) == any(CodeUint) {
			return 403, true
		}
	}
	return 0, false
}

// GetGrpcCode 返回错误对应的gRPC状态码
func GetGrpcCode[T comparable](v T) (codes.Code, bool) {
	switch val := any(v).(type) {
	case error:
		if errors.Is(val, ErrMixed1) {
			return codes.NotFound, true
		}
		if errors.Is(val, ErrMixed2) {
			return codes.Internal, true
		}
	default:
		if any(val) == any(CodeInt) {
			return codes.OK, true
		}
		if any(val) == any(CodeInt32) {
			return codes.OK, true
		}
		if any(val) == any(CodeInt64) {
			return codes.InvalidArgument, true
		}
		if any(val) == any(CodeUint) {
			return codes.PermissionDenied, true
		}
	}
	return codes.Unknown, false
}

// GetCode 返回业务错误码
func GetCode[T comparable](v T) (int, bool) {
	switch val := any(v).(type) {
	case error:
		if errors.Is(val, ErrMixed1) {
			return 60001, true
		}
		if errors.Is(val, ErrMixed2) {
			return 60002, true
		}
	default:
		if any(val) == any(CodeInt) {
			return 60003, true
		}
		if any(val) == any(CodeInt32) {
			return 60004, true
		}
		if any(val) == any(CodeInt64) {
			return 60005, true
		}
		if any(val) == any(CodeUint) {
			return 60006, true
		}
	}
	return 0, false
}

// GetName 返回变量名
func GetName[T comparable](v T) (string, bool) {
	switch val := any(v).(type) {
	case error:
		if errors.Is(val, ErrMixed1) {
			return "ErrMixed1", true
		}
		if errors.Is(val, ErrMixed2) {
			return "ErrMixed2", true
		}
	default:
		if any(val) == any(CodeInt) {
			return "CodeInt", true
		}
		if any(val) == any(CodeInt32) {
			return "CodeInt32", true
		}
		if any(val) == any(CodeInt64) {
			return "CodeInt64", true
		}
		if any(val) == any(CodeUint) {
			return "CodeUint", true
		}
	}
	return "", false
}
