// Code generated by gogen. DO NOT EDIT.
package testdata

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// ================ mockgen ================

// MockGenericRepository is a mock of GenericRepository interface.
type MockGenericRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockGenericRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockGenericRepositoryMockRecorder is the mock recorder for MockGenericRepository.
type MockGenericRepositoryMockRecorder[T any] struct {
	mock *MockGenericRepository[T]
}

// NewMockGenericRepository creates a new mock instance.
func NewMockGenericRepository[T any](ctrl *gomock.Controller) *MockGenericRepository[T] {
	mock := &MockGenericRepository[T]{ctrl: ctrl}
	mock.recorder = &MockGenericRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericRepository[T]) EXPECT() *MockGenericRepositoryMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockGenericRepository[T]) Get(ctx context.Context, id int64) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGenericRepositoryMockRecorder[T]) Get(ctx, id any) *MockGenericRepositoryGetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGenericRepository[T])(nil).Get), ctx, id)
	return &MockGenericRepositoryGetCall[T]{Call: call}
}

// MockGenericRepositoryGetCall wrap *gomock.Call
type MockGenericRepositoryGetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGenericRepositoryGetCall[T]) Return(arg0 T, arg1 error) *MockGenericRepositoryGetCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGenericRepositoryGetCall[T]) Do(f func(context.Context, int64) (T, error)) *MockGenericRepositoryGetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGenericRepositoryGetCall[T]) DoAndReturn(f func(context.Context, int64) (T, error)) *MockGenericRepositoryGetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockGenericRepository[T]) List(ctx context.Context, opts ...ListOption) ([]T, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGenericRepositoryMockRecorder[T]) List(ctx any, opts ...any) *MockGenericRepositoryListCall[T] {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGenericRepository[T])(nil).List), varargs...)
	return &MockGenericRepositoryListCall[T]{Call: call}
}

// MockGenericRepositoryListCall wrap *gomock.Call
type MockGenericRepositoryListCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGenericRepositoryListCall[T]) Return(arg0 []T, arg1 error) *MockGenericRepositoryListCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGenericRepositoryListCall[T]) Do(f func(context.Context, ...ListOption) ([]T, error)) *MockGenericRepositoryListCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGenericRepositoryListCall[T]) DoAndReturn(f func(context.Context, ...ListOption) ([]T, error)) *MockGenericRepositoryListCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockGenericRepository[T]) Save(ctx context.Context, entity T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGenericRepositoryMockRecorder[T]) Save(ctx, entity any) *MockGenericRepositorySaveCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGenericRepository[T])(nil).Save), ctx, entity)
	return &MockGenericRepositorySaveCall[T]{Call: call}
}

// MockGenericRepositorySaveCall wrap *gomock.Call
type MockGenericRepositorySaveCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGenericRepositorySaveCall[T]) Return(arg0 error) *MockGenericRepositorySaveCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGenericRepositorySaveCall[T]) Do(f func(context.Context, T) error) *MockGenericRepositorySaveCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGenericRepositorySaveCall[T]) DoAndReturn(f func(context.Context, T) error) *MockGenericRepositorySaveCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", msg)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any) *MockLoggerDebugCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), msg)
	return &MockLoggerDebugCall{Call: call}
}

// MockLoggerDebugCall wrap *gomock.Call
type MockLoggerDebugCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoggerDebugCall) Return() *MockLoggerDebugCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoggerDebugCall) Do(f func(string)) *MockLoggerDebugCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoggerDebugCall) DoAndReturn(f func(string)) *MockLoggerDebugCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, args ...any) *MockLoggerErrorCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
	return &MockLoggerErrorCall{Call: call}
}

// MockLoggerErrorCall wrap *gomock.Call
type MockLoggerErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoggerErrorCall) Return() *MockLoggerErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoggerErrorCall) Do(f func(string, ...any)) *MockLoggerErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoggerErrorCall) DoAndReturn(f func(string, ...any)) *MockLoggerErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, args ...any) *MockLoggerInfoCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
	return &MockLoggerInfoCall{Call: call}
}

// MockLoggerInfoCall wrap *gomock.Call
type MockLoggerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoggerInfoCall) Return() *MockLoggerInfoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoggerInfoCall) Do(f func(string, ...any)) *MockLoggerInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoggerInfoCall) DoAndReturn(f func(string, ...any)) *MockLoggerInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, user *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, user any) *MockUserServiceCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, user)
	return &MockUserServiceCreateUserCall{Call: call}
}

// MockUserServiceCreateUserCall wrap *gomock.Call
type MockUserServiceCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceCreateUserCall) Return(arg0 error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceCreateUserCall) Do(f func(context.Context, *User) error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceCreateUserCall) DoAndReturn(f func(context.Context, *User) error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, id any) *MockUserServiceDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, id)
	return &MockUserServiceDeleteUserCall{Call: call}
}

// MockUserServiceDeleteUserCall wrap *gomock.Call
type MockUserServiceDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceDeleteUserCall) Return(arg0 error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceDeleteUserCall) Do(f func(context.Context, int64) error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceDeleteUserCall) DoAndReturn(f func(context.Context, int64) error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(ctx context.Context, id int64) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(ctx, id any) *MockUserServiceGetUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), ctx, id)
	return &MockUserServiceGetUserCall{Call: call}
}

// MockUserServiceGetUserCall wrap *gomock.Call
type MockUserServiceGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceGetUserCall) Return(arg0 *User, arg1 error) *MockUserServiceGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceGetUserCall) Do(f func(context.Context, int64) (*User, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceGetUserCall) DoAndReturn(f func(context.Context, int64) (*User, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CustomMockRepo is a mock of UserRepository interface.
type CustomMockRepo struct {
	ctrl     *gomock.Controller
	recorder *CustomMockRepoMockRecorder
	isgomock struct{}
}

// CustomMockRepoMockRecorder is the mock recorder for CustomMockRepo.
type CustomMockRepoMockRecorder struct {
	mock *CustomMockRepo
}

// NewCustomMockRepo creates a new mock instance.
func NewCustomMockRepo(ctrl *gomock.Controller) *CustomMockRepo {
	mock := &CustomMockRepo{ctrl: ctrl}
	mock.recorder = &CustomMockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CustomMockRepo) EXPECT() *CustomMockRepoMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *CustomMockRepo) FindByID(id int64) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *CustomMockRepoMockRecorder) FindByID(id any) *CustomMockRepoFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*CustomMockRepo)(nil).FindByID), id)
	return &CustomMockRepoFindByIDCall{Call: call}
}

// CustomMockRepoFindByIDCall wrap *gomock.Call
type CustomMockRepoFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CustomMockRepoFindByIDCall) Return(arg0 *User, arg1 error) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CustomMockRepoFindByIDCall) Do(f func(int64) (*User, error)) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CustomMockRepoFindByIDCall) DoAndReturn(f func(int64) (*User, error)) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *CustomMockRepo) Save(user *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *CustomMockRepoMockRecorder) Save(user any) *CustomMockRepoSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*CustomMockRepo)(nil).Save), user)
	return &CustomMockRepoSaveCall{Call: call}
}

// CustomMockRepoSaveCall wrap *gomock.Call
type CustomMockRepoSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CustomMockRepoSaveCall) Return(arg0 error) *CustomMockRepoSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CustomMockRepoSaveCall) Do(f func(*User) error) *CustomMockRepoSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CustomMockRepoSaveCall) DoAndReturn(f func(*User) error) *CustomMockRepoSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReadWriter is a mock of ReadWriter interface.
type MockReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriterMockRecorder
	isgomock struct{}
}

// MockReadWriterMockRecorder is the mock recorder for MockReadWriter.
type MockReadWriterMockRecorder struct {
	mock *MockReadWriter
}

// NewMockReadWriter creates a new mock instance.
func NewMockReadWriter(ctrl *gomock.Controller) *MockReadWriter {
	mock := &MockReadWriter{ctrl: ctrl}
	mock.recorder = &MockReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriter) EXPECT() *MockReadWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReadWriterMockRecorder) Close() *MockReadWriterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadWriter)(nil).Close))
	return &MockReadWriterCloseCall{Call: call}
}

// MockReadWriterCloseCall wrap *gomock.Call
type MockReadWriterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadWriterCloseCall) Return(arg0 error) *MockReadWriterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadWriterCloseCall) Do(f func() error) *MockReadWriterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadWriterCloseCall) DoAndReturn(f func() error) *MockReadWriterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockReadWriter) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadWriterMockRecorder) Read(p any) *MockReadWriterReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadWriter)(nil).Read), p)
	return &MockReadWriterReadCall{Call: call}
}

// MockReadWriterReadCall wrap *gomock.Call
type MockReadWriterReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadWriterReadCall) Return(n int, err error) *MockReadWriterReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadWriterReadCall) Do(f func([]byte) (int, error)) *MockReadWriterReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadWriterReadCall) DoAndReturn(f func([]byte) (int, error)) *MockReadWriterReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *MockReadWriter) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockReadWriterMockRecorder) Write(p any) *MockReadWriterWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockReadWriter)(nil).Write), p)
	return &MockReadWriterWriteCall{Call: call}
}

// MockReadWriterWriteCall wrap *gomock.Call
type MockReadWriterWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadWriterWriteCall) Return(n int, err error) *MockReadWriterWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadWriterWriteCall) Do(f func([]byte) (int, error)) *MockReadWriterWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadWriterWriteCall) DoAndReturn(f func([]byte) (int, error)) *MockReadWriterWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockIOReadWriter is a mock of IOReadWriter interface.
type MockIOReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIOReadWriterMockRecorder
	isgomock struct{}
}

// MockIOReadWriterMockRecorder is the mock recorder for MockIOReadWriter.
type MockIOReadWriterMockRecorder struct {
	mock *MockIOReadWriter
}

// NewMockIOReadWriter creates a new mock instance.
func NewMockIOReadWriter(ctrl *gomock.Controller) *MockIOReadWriter {
	mock := &MockIOReadWriter{ctrl: ctrl}
	mock.recorder = &MockIOReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOReadWriter) EXPECT() *MockIOReadWriterMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockIOReadWriter) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockIOReadWriterMockRecorder) Read(p any) *MockIOReadWriterReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockIOReadWriter)(nil).Read), p)
	return &MockIOReadWriterReadCall{Call: call}
}

// MockIOReadWriterReadCall wrap *gomock.Call
type MockIOReadWriterReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOReadWriterReadCall) Return(n int, err error) *MockIOReadWriterReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOReadWriterReadCall) Do(f func([]byte) (int, error)) *MockIOReadWriterReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOReadWriterReadCall) DoAndReturn(f func([]byte) (int, error)) *MockIOReadWriterReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sync mocks base method.
func (m *MockIOReadWriter) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockIOReadWriterMockRecorder) Sync() *MockIOReadWriterSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockIOReadWriter)(nil).Sync))
	return &MockIOReadWriterSyncCall{Call: call}
}

// MockIOReadWriterSyncCall wrap *gomock.Call
type MockIOReadWriterSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOReadWriterSyncCall) Return(arg0 error) *MockIOReadWriterSyncCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOReadWriterSyncCall) Do(f func() error) *MockIOReadWriterSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOReadWriterSyncCall) DoAndReturn(f func() error) *MockIOReadWriterSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *MockIOReadWriter) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockIOReadWriterMockRecorder) Write(p any) *MockIOReadWriterWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockIOReadWriter)(nil).Write), p)
	return &MockIOReadWriterWriteCall{Call: call}
}

// MockIOReadWriterWriteCall wrap *gomock.Call
type MockIOReadWriterWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIOReadWriterWriteCall) Return(n int, err error) *MockIOReadWriterWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIOReadWriterWriteCall) Do(f func([]byte) (int, error)) *MockIOReadWriterWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIOReadWriterWriteCall) DoAndReturn(f func([]byte) (int, error)) *MockIOReadWriterWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockNamedReturnsInterface is a mock of NamedReturnsInterface interface.
type MockNamedReturnsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNamedReturnsInterfaceMockRecorder
	isgomock struct{}
}

// MockNamedReturnsInterfaceMockRecorder is the mock recorder for MockNamedReturnsInterface.
type MockNamedReturnsInterfaceMockRecorder struct {
	mock *MockNamedReturnsInterface
}

// NewMockNamedReturnsInterface creates a new mock instance.
func NewMockNamedReturnsInterface(ctrl *gomock.Controller) *MockNamedReturnsInterface {
	mock := &MockNamedReturnsInterface{ctrl: ctrl}
	mock.recorder = &MockNamedReturnsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamedReturnsInterface) EXPECT() *MockNamedReturnsInterfaceMockRecorder {
	return m.recorder
}

// GetData mocks base method.
func (m *MockNamedReturnsInterface) GetData(key string) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetData indicates an expected call of GetData.
func (mr *MockNamedReturnsInterfaceMockRecorder) GetData(key any) *MockNamedReturnsInterfaceGetDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockNamedReturnsInterface)(nil).GetData), key)
	return &MockNamedReturnsInterfaceGetDataCall{Call: call}
}

// MockNamedReturnsInterfaceGetDataCall wrap *gomock.Call
type MockNamedReturnsInterfaceGetDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNamedReturnsInterfaceGetDataCall) Return(data []byte, found bool, err error) *MockNamedReturnsInterfaceGetDataCall {
	c.Call = c.Call.Return(data, found, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNamedReturnsInterfaceGetDataCall) Do(f func(string) ([]byte, bool, error)) *MockNamedReturnsInterfaceGetDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNamedReturnsInterfaceGetDataCall) DoAndReturn(f func(string) ([]byte, bool, error)) *MockNamedReturnsInterfaceGetDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Process mocks base method.
func (m *MockNamedReturnsInterface) Process(input string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockNamedReturnsInterfaceMockRecorder) Process(input any) *MockNamedReturnsInterfaceProcessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockNamedReturnsInterface)(nil).Process), input)
	return &MockNamedReturnsInterfaceProcessCall{Call: call}
}

// MockNamedReturnsInterfaceProcessCall wrap *gomock.Call
type MockNamedReturnsInterfaceProcessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNamedReturnsInterfaceProcessCall) Return(arg0 string, arg1 error) *MockNamedReturnsInterfaceProcessCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNamedReturnsInterfaceProcessCall) Do(f func(string) (string, error)) *MockNamedReturnsInterfaceProcessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNamedReturnsInterfaceProcessCall) DoAndReturn(f func(string) (string, error)) *MockNamedReturnsInterfaceProcessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSameTypeReturns is a mock of SameTypeReturns interface.
type MockSameTypeReturns struct {
	ctrl     *gomock.Controller
	recorder *MockSameTypeReturnsMockRecorder
	isgomock struct{}
}

// MockSameTypeReturnsMockRecorder is the mock recorder for MockSameTypeReturns.
type MockSameTypeReturnsMockRecorder struct {
	mock *MockSameTypeReturns
}

// NewMockSameTypeReturns creates a new mock instance.
func NewMockSameTypeReturns(ctrl *gomock.Controller) *MockSameTypeReturns {
	mock := &MockSameTypeReturns{ctrl: ctrl}
	mock.recorder = &MockSameTypeReturnsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSameTypeReturns) EXPECT() *MockSameTypeReturnsMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockSameTypeReturns) CreateWallet(ctx context.Context) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockSameTypeReturnsMockRecorder) CreateWallet(ctx any) *MockSameTypeReturnsCreateWalletCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockSameTypeReturns)(nil).CreateWallet), ctx)
	return &MockSameTypeReturnsCreateWalletCall{Call: call}
}

// MockSameTypeReturnsCreateWalletCall wrap *gomock.Call
type MockSameTypeReturnsCreateWalletCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSameTypeReturnsCreateWalletCall) Return(publicKey, rawPublicKey, refID string, err error) *MockSameTypeReturnsCreateWalletCall {
	c.Call = c.Call.Return(publicKey, rawPublicKey, refID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSameTypeReturnsCreateWalletCall) Do(f func(context.Context) (string, string, string, error)) *MockSameTypeReturnsCreateWalletCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSameTypeReturnsCreateWalletCall) DoAndReturn(f func(context.Context) (string, string, string, error)) *MockSameTypeReturnsCreateWalletCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
