// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ubuntu/Projects/go/cuti/gogen/mockgen/example/interfaces.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, user *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, user any) *MockUserServiceCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, user)
	return &MockUserServiceCreateUserCall{Call: call}
}

// MockUserServiceCreateUserCall wrap *gomock.Call
type MockUserServiceCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceCreateUserCall) Return(arg0 error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceCreateUserCall) Do(f func(context.Context, *User) error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceCreateUserCall) DoAndReturn(f func(context.Context, *User) error) *MockUserServiceCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, id any) *MockUserServiceDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, id)
	return &MockUserServiceDeleteUserCall{Call: call}
}

// MockUserServiceDeleteUserCall wrap *gomock.Call
type MockUserServiceDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceDeleteUserCall) Return(arg0 error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceDeleteUserCall) Do(f func(context.Context, int64) error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceDeleteUserCall) DoAndReturn(f func(context.Context, int64) error) *MockUserServiceDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(ctx context.Context, id int64) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(ctx, id any) *MockUserServiceGetUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), ctx, id)
	return &MockUserServiceGetUserCall{Call: call}
}

// MockUserServiceGetUserCall wrap *gomock.Call
type MockUserServiceGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserServiceGetUserCall) Return(arg0 *User, arg1 error) *MockUserServiceGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserServiceGetUserCall) Do(f func(context.Context, int64) (*User, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserServiceGetUserCall) DoAndReturn(f func(context.Context, int64) (*User, error)) *MockUserServiceGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CustomMockRepo is a mock of UserRepository interface.
type CustomMockRepo struct {
	ctrl     *gomock.Controller
	recorder *CustomMockRepoMockRecorder
	isgomock struct{}
}

// CustomMockRepoMockRecorder is the mock recorder for CustomMockRepo.
type CustomMockRepoMockRecorder struct {
	mock *CustomMockRepo
}

// NewCustomMockRepo creates a new mock instance.
func NewCustomMockRepo(ctrl *gomock.Controller) *CustomMockRepo {
	mock := &CustomMockRepo{ctrl: ctrl}
	mock.recorder = &CustomMockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CustomMockRepo) EXPECT() *CustomMockRepoMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *CustomMockRepo) FindByID(id int64) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *CustomMockRepoMockRecorder) FindByID(id any) *CustomMockRepoFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*CustomMockRepo)(nil).FindByID), id)
	return &CustomMockRepoFindByIDCall{Call: call}
}

// CustomMockRepoFindByIDCall wrap *gomock.Call
type CustomMockRepoFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CustomMockRepoFindByIDCall) Return(arg0 *User, arg1 error) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CustomMockRepoFindByIDCall) Do(f func(int64) (*User, error)) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CustomMockRepoFindByIDCall) DoAndReturn(f func(int64) (*User, error)) *CustomMockRepoFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *CustomMockRepo) Save(user *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *CustomMockRepoMockRecorder) Save(user any) *CustomMockRepoSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*CustomMockRepo)(nil).Save), user)
	return &CustomMockRepoSaveCall{Call: call}
}

// CustomMockRepoSaveCall wrap *gomock.Call
type CustomMockRepoSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CustomMockRepoSaveCall) Return(arg0 error) *CustomMockRepoSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CustomMockRepoSaveCall) Do(f func(*User) error) *CustomMockRepoSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CustomMockRepoSaveCall) DoAndReturn(f func(*User) error) *CustomMockRepoSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
