// Code generated by gogen. DO NOT EDIT.
package prefix

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type AccountSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	fieldType AccountPO
	alias     string
	tableName string
}

func (t AccountSchemaType) TableName() string {
	return t.tableName
}

func (t AccountSchemaType) Alias() string {
	return t.alias
}

func (t *AccountSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
}

func (t AccountSchemaType) As(alias string) AccountSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t AccountSchemaType) ModelType() *AccountPO {
	return &t.fieldType
}

func (t AccountSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t AccountSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
	}
}

func (t AccountSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var AccountSchema = AccountSchemaType{
	tableName: "accounts",
	ID:        gsql.IntFieldOf[uint64]("accounts", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("accounts", "name"),
	fieldType: AccountPO{},
}

type MyAppOrderSchemaType struct {
	ID          gsql.IntField[uint64]
	UserID      gsql.IntField[uint64]
	TotalAmount gsql.FloatField[float64]
	Status      gsql.IntField[int]
	CreatedAt   gsql.DateTimeField[time.Time]
	fieldType   Order
	alias       string
	tableName   string
}

func (t MyAppOrderSchemaType) TableName() string {
	return t.tableName
}

func (t MyAppOrderSchemaType) Alias() string {
	return t.alias
}

func (t *MyAppOrderSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
	t.TotalAmount = t.TotalAmount.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t MyAppOrderSchemaType) As(alias string) MyAppOrderSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t MyAppOrderSchemaType) ModelType() *Order {
	return &t.fieldType
}

func (t MyAppOrderSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t MyAppOrderSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.UserID,
		t.TotalAmount,
		t.Status,
		t.CreatedAt,
	}
}

func (t MyAppOrderSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var MyAppOrderSchema = MyAppOrderSchemaType{
	tableName:   "orders",
	ID:          gsql.IntFieldOf[uint64]("orders", "id", field.FlagPrimaryKey),
	UserID:      gsql.IntFieldOf[uint64]("orders", "user_id"),
	TotalAmount: gsql.FloatFieldOf[float64]("orders", "total_amount"),
	Status:      gsql.IntFieldOf[int]("orders", "status"),
	CreatedAt:   gsql.DateTimeFieldOf[time.Time]("orders", "created_at"),
	fieldType:   Order{},
}

type TbProductSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Price     gsql.FloatField[float64]
	fieldType Product
	alias     string
	tableName string
}

func (t TbProductSchemaType) TableName() string {
	return t.tableName
}

func (t TbProductSchemaType) Alias() string {
	return t.alias
}

func (t *TbProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
}

func (t TbProductSchemaType) As(alias string) TbProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t TbProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t TbProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t TbProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Price,
	}
}

func (t TbProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var TbProductSchema = TbProductSchemaType{
	tableName: "products",
	ID:        gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("products", "name"),
	Price:     gsql.FloatFieldOf[float64]("products", "price"),
	fieldType: Product{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Email     gsql.StringField[string]
	CreatedAt gsql.DateTimeField[time.Time]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.CreatedAt,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("users", "name"),
	Email:     gsql.StringFieldOf[string]("users", "email"),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("users", "created_at"),
	fieldType: User{},
}
