// Code generated by gogen. DO NOT EDIT.
package basic

import (
	"io"
	"time"
)

// ================ templategen ================

// RetryService Getters
// Description: 带有重试功能的服务

func (s *RetryService) GetMaxRetries() int {
	return s.maxRetries
}

func (s *RetryService) GetRetryDelay() time.Duration {
	return s.retryDelay
}

// Service Getters
// Description: 带有配置的服务

func (s *Service) GetReader() io.Reader {
	return s.reader
}

func (s *Service) GetTimeout() time.Duration {
	return s.timeout
}

func (s *Service) GetName() string {
	return s.name
}
