// Code generated by gogen. DO NOT EDIT.
package no_name

import "errors"

// ================ stateflow ================

// Phase 阶段枚举
type Phase string

const (
	PhasePending  Phase = "pending"
	PhaseApproved Phase = "approved"
	PhaseRejected Phase = "rejected"
	PhaseDone     Phase = "done"
)

var PhaseEnums = struct {
	Pending  Phase
	Approved Phase
	Rejected Phase
	Done     Phase
}{
	Pending:  PhasePending,
	Approved: PhaseApproved,
	Rejected: PhaseRejected,
	Done:     PhaseDone,
}

// Stage 阶段（Phase + Status）
type Stage = Phase

// 预定义阶段
var (
	StagePending  = PhasePending
	StageApproved = PhaseApproved
	StageRejected = PhaseRejected
	StageDone     = PhaseDone
)

// State 完整状态
type State struct {
	Current Stage `json:"current"`
}

// StateColumns 数据库存储结构
type StateColumns struct {
	Phase Phase `gorm:"column:phase" json:"phase"`
}

func (s State) ToColumns() StateColumns {
	return StateColumns{
		Phase: s.Current,
	}
}

func (c StateColumns) ToState() State {
	return State{
		Current: c.Phase,
	}
}

// 错误定义
var ErrInvalidTransition = errors.New("invalid transition")

func (s State) TransitionTo(to Stage) (State, error) {
	switch s.Current {
	case StagePending:
		switch to {
		case StageApproved:
			return State{Current: to}, nil
		case StageRejected:
			return State{Current: to}, nil
		}
	case StageApproved:
		switch to {
		case StageDone:
			return State{Current: to}, nil
		}
	case StageRejected:
		switch to {
		case StagePending:
			return State{Current: to}, nil
		}
	}
	return s, ErrInvalidTransition
}

func (s State) ValidTransitions() []Stage {
	switch s.Current {
	case StagePending:
		return []Stage{StageApproved, StageRejected}
	case StageApproved:
		return []Stage{StageDone}
	case StageRejected:
		return []Stage{StagePending}
	}
	return nil
}
