// Code generated by gogen. DO NOT EDIT.
package v2api

import "time"

// ================ pickgen ================

// RequestBasic 从 Request Pick 生成
type RequestBasic struct {
	ID      string            `json:"id"`
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers"`
}

// From 从 Request 复制字段值
func (t *RequestBasic) From(src *Request) {
	t.ID = src.ID
	t.Method = src.Method
	t.Path = src.Path
	t.Headers = src.Headers
}

// NewRequestBasic 从 Request 创建 RequestBasic
func NewRequestBasic(src *Request) RequestBasic {
	var result RequestBasic
	result.From(src)
	return result
}

// ResponseSummary 从 Response Pick 生成
type ResponseSummary struct {
	ID         string        `json:"id"`
	StatusCode int           `json:"status_code"`
	Duration   time.Duration `json:"duration"`
}

// From 从 Response 复制字段值
func (t *ResponseSummary) From(src *Response) {
	t.ID = src.ID
	t.StatusCode = src.StatusCode
	t.Duration = src.Duration
}

// NewResponseSummary 从 Response 创建 ResponseSummary
func NewResponseSummary(src *Response) ResponseSummary {
	var result ResponseSummary
	result.From(src)
	return result
}

// ================ omitgen ================

// RequestPublic 从 Request Omit 生成
type RequestPublic struct {
	ID        string            `json:"id"`
	Method    string            `json:"method"`
	Path      string            `json:"path"`
	Headers   map[string]string `json:"headers"`
	Body      []byte            `json:"body"`
	Timestamp time.Time         `json:"timestamp"`
}

// From 从 Request 复制字段值
func (t *RequestPublic) From(src *Request) {
	t.ID = src.ID
	t.Method = src.Method
	t.Path = src.Path
	t.Headers = src.Headers
	t.Body = src.Body
	t.Timestamp = src.Timestamp
}

// NewRequestPublic 从 Request 创建 RequestPublic
func NewRequestPublic(src *Request) RequestPublic {
	var result RequestPublic
	result.From(src)
	return result
}
