package settergen

import (
	"fmt"
	"testing"

	"github.com/donutnomad/gg"
	"github.com/donutnomad/gogen/internal/utils"
)

// TestBugRemoveUnusedSingleImportAlias 测试当 merge 后 domain 包被误判为未使用时的情况
// 模拟 mergeDefinitionsWithSeparator 生成的代码
func TestBugRemoveUnusedSingleImportAlias(t *testing.T) {
	// 模拟 mergeDefinitionsWithSeparator 最终输出的内容
	// settergen 生成器的 def 只有一个 import: domain
	// 合并后 merged 也只有一个 import
	merged := gg.New()
	merged.SetHeader("Code generated by gogen. DO NOT EDIT.")
	merged.SetPackage("emailroutingrepo")

	// settergen 的 def
	def := gg.New()
	def.SetPackage("emailroutingrepo")
	def.PAlias("github.com/example/emailrouting", "domain")
	funcCode := `// Missing fields: default_id, deleted_at
func (e *EmailRoutingPO) ToPatch(input *domain.EmailRouting) map[string]any {
	b := e.ToPO(input)
	fields := input.ExportPatch()
	values := make(map[string]any, 9)
	if fields.ID.IsPresent() {
		values["id"] = b.Model.ID
	}
	return values
}
`
	def.Body().AddString(funcCode)

	// 模拟 mergeDefinitionsWithSeparator 的过程
	separator := "// ================ settergen ================"
	merged.Body().AddLine()
	merged.Body().AddString(separator)
	merged.Body().AddLine()
	merged.Merge(def)

	src := merged.Bytes()
	fmt.Println("=== Raw bytes from merged.Bytes() ===")
	fmt.Println(string(src))

	tmpFile := t.TempDir() + "/test_generate.go"
	err := utils.WriteFormat(tmpFile, src)
	if err != nil {
		t.Errorf("WriteFormat 失败（重现了 bug）: %v", err)
	} else {
		t.Log("WriteFormat 成功")
	}
}
