package settergen

import (
	"fmt"
	"testing"

	"github.com/donutnomad/gg"
	"github.com/donutnomad/gogen/internal/utils"
)

// TestBugFormatSingleAliasImport 测试单个带别名 import 的格式化
// 重现 "format file failed: expected declaration, found domain" bug
func TestBugFormatSingleAliasImport(t *testing.T) {
	gen := gg.New()
	gen.SetHeader("Code generated by gogen. DO NOT EDIT.")
	gen.SetPackage("emailroutingrepo")
	gen.PAlias("github.com/example/emailrouting", "domain")

	funcCode := `// Missing fields: default_id, deleted_at
func (e *EmailRoutingPO) ToPatch(input *domain.EmailRouting) map[string]any {
	b := e.ToPO(input)
	fields := input.ExportPatch()
	values := make(map[string]any, 9)
	if fields.ID.IsPresent() {
		values["id"] = b.Model.ID
	}
	return values
}
`
	gen.Body().AddString(funcCode)

	src := gen.Bytes()
	fmt.Println("=== Raw bytes from gen.Bytes() ===")
	fmt.Println(string(src))

	// 测试 WriteFormat 是否会失败
	tmpFile := t.TempDir() + "/test_generate.go"
	err := utils.WriteFormat(tmpFile, src)
	if err != nil {
		t.Errorf("WriteFormat 失败: %v", err)
	} else {
		t.Log("WriteFormat 成功")
	}
}
