// Code generated by gogen. DO NOT EDIT.
package json_types

import (
	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
	"gorm.io/datatypes"
)

// ================ gormgen ================

type ArticleSchemaType struct {
	ID         gsql.IntField[uint64]
	Title      gsql.StringField[string]
	RawContent gsql.ScalarField[datatypes.JSON]
	fieldType  Article
	alias      string
	tableName  string
}

func (t ArticleSchemaType) TableName() string {
	return t.tableName
}

func (t ArticleSchemaType) Alias() string {
	return t.alias
}

func (t *ArticleSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Title = t.Title.WithTable(&tn)
	t.RawContent = t.RawContent.WithTable(&tn)
}

func (t ArticleSchemaType) As(alias string) ArticleSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ArticleSchemaType) ModelType() *Article {
	return &t.fieldType
}

func (t ArticleSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ArticleSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Title,
		t.RawContent,
	}
}

func (t ArticleSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ArticleSchema = ArticleSchemaType{
	tableName:  "articles",
	ID:         gsql.IntFieldOf[uint64]("articles", "id", field.FlagPrimaryKey),
	Title:      gsql.StringFieldOf[string]("articles", "title"),
	RawContent: gsql.ScalarFieldOf[datatypes.JSON]("articles", "raw_content"),
	fieldType:  Article{},
}

type ProductSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Tags      gsql.ScalarField[datatypes.JSONSlice[string]]
	Images    gsql.ScalarField[datatypes.JSONSlice[string]]
	fieldType Product
	alias     string
	tableName string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Tags = t.Tags.WithTable(&tn)
	t.Images = t.Images.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Tags,
		t.Images,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName: "products",
	ID:        gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("products", "name"),
	Tags:      gsql.ScalarFieldOf[datatypes.JSONSlice[string]]("products", "tags"),
	Images:    gsql.ScalarFieldOf[datatypes.JSONSlice[string]]("products", "images"),
	fieldType: Product{},
}

type UserSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Settings  gsql.ScalarField[datatypes.JSONType[Settings]]
	Metadata  gsql.ScalarField[datatypes.JSONType[Metadata]]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Settings = t.Settings.WithTable(&tn)
	t.Metadata = t.Metadata.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Settings,
		t.Metadata,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        gsql.IntFieldOf[uint64]("users", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("users", "name"),
	Settings:  gsql.ScalarFieldOf[datatypes.JSONType[Settings]]("users", "settings"),
	Metadata:  gsql.ScalarFieldOf[datatypes.JSONType[Metadata]]("users", "metadata"),
	fieldType: User{},
}
