// Code generated by gogen. DO NOT EDIT.
package pointer_types

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type EventSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	StartTime gsql.DateTimeField[*time.Time]
	EventDate gsql.DateField[*time.Time]
	Duration  gsql.TimeField[*time.Time]
	fieldType Event
	alias     string
	tableName string
}

func (t EventSchemaType) TableName() string {
	return t.tableName
}

func (t EventSchemaType) Alias() string {
	return t.alias
}

func (t *EventSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.StartTime = t.StartTime.WithTable(&tn)
	t.EventDate = t.EventDate.WithTable(&tn)
	t.Duration = t.Duration.WithTable(&tn)
}

func (t EventSchemaType) As(alias string) EventSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t EventSchemaType) ModelType() *Event {
	return &t.fieldType
}

func (t EventSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t EventSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.StartTime,
		t.EventDate,
		t.Duration,
	}
}

func (t EventSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var EventSchema = EventSchemaType{
	tableName: "events",
	ID:        gsql.IntFieldOf[uint64]("events", "id", field.FlagPrimaryKey),
	Name:      gsql.StringFieldOf[string]("events", "name"),
	StartTime: gsql.DateTimeFieldOf[*time.Time]("events", "start_time"),
	EventDate: gsql.DateFieldOf[*time.Time]("events", "event_date"),
	Duration:  gsql.TimeFieldOf[*time.Time]("events", "duration"),
	fieldType: Event{},
}

type ProductSchemaType struct {
	ID          gsql.IntField[uint64]
	Name        gsql.StringField[string]
	Description gsql.StringField[*string]
	Price       gsql.FloatField[*float64]
	Stock       gsql.IntField[*int]
	IsActive    gsql.IntField[*bool]
	Weight      gsql.FloatField[*float32]
	CategoryID  gsql.IntField[*uint64]
	fieldType   Product
	alias       string
	tableName   string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Description = t.Description.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
	t.Stock = t.Stock.WithTable(&tn)
	t.IsActive = t.IsActive.WithTable(&tn)
	t.Weight = t.Weight.WithTable(&tn)
	t.CategoryID = t.CategoryID.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Description,
		t.Price,
		t.Stock,
		t.IsActive,
		t.Weight,
		t.CategoryID,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName:   "products",
	ID:          gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey),
	Name:        gsql.StringFieldOf[string]("products", "name"),
	Description: gsql.StringFieldOf[*string]("products", "description"),
	Price:       gsql.FloatFieldOf[*float64]("products", "price"),
	Stock:       gsql.IntFieldOf[*int]("products", "stock"),
	IsActive:    gsql.IntFieldOf[*bool]("products", "is_active"),
	Weight:      gsql.FloatFieldOf[*float32]("products", "weight"),
	CategoryID:  gsql.IntFieldOf[*uint64]("products", "category_id"),
	fieldType:   Product{},
}
