// Code generated by gogen. DO NOT EDIT.
package multiple

import "time"

// ================ pickgen ================

// AccountBasic 从 Account Pick 生成
type AccountBasic struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Name  string `json:"name" gorm:"column:name;size:100"`
	Email string `json:"email" gorm:"column:email;uniqueIndex"`
}

// From 从 Account 复制字段值
func (t *AccountBasic) From(src *Account) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
}

// NewAccountBasic 从 Account 创建 AccountBasic
func NewAccountBasic(src *Account) AccountBasic {
	var result AccountBasic
	result.From(src)
	return result
}

// AccountFull 从 Account Pick 生成
type AccountFull struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Name      string    `json:"name" gorm:"column:name;size:100"`
	Email     string    `json:"email" gorm:"column:email;uniqueIndex"`
	Phone     string    `json:"phone" gorm:"column:phone;size:20"`
	Address   string    `json:"address" gorm:"column:address;size:255"`
	Balance   float64   `json:"balance" gorm:"column:balance"`
	Status    string    `json:"status" gorm:"column:status;size:20"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Account 复制字段值
func (t *AccountFull) From(src *Account) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.Phone = src.Phone
	t.Address = src.Address
	t.Balance = src.Balance
	t.Status = src.Status
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewAccountFull 从 Account 创建 AccountFull
func NewAccountFull(src *Account) AccountFull {
	var result AccountFull
	result.From(src)
	return result
}

// AccountID 从 Account Pick 生成
type AccountID struct {
	ID uint64 `json:"id" gorm:"primaryKey"`
}

// From 从 Account 复制字段值
func (t *AccountID) From(src *Account) {
	t.ID = src.ID
}

// NewAccountID 从 Account 创建 AccountID
func NewAccountID(src *Account) AccountID {
	var result AccountID
	result.From(src)
	return result
}

// AccountProfile 从 Account Pick 生成
type AccountProfile struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Name      string    `json:"name" gorm:"column:name;size:100"`
	Email     string    `json:"email" gorm:"column:email;uniqueIndex"`
	Phone     string    `json:"phone" gorm:"column:phone;size:20"`
	Address   string    `json:"address" gorm:"column:address;size:255"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
}

// From 从 Account 复制字段值
func (t *AccountProfile) From(src *Account) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.Phone = src.Phone
	t.Address = src.Address
	t.CreatedAt = src.CreatedAt
}

// NewAccountProfile 从 Account 创建 AccountProfile
func NewAccountProfile(src *Account) AccountProfile {
	var result AccountProfile
	result.From(src)
	return result
}

// PermissionBasic 从 Permission Pick 生成
type PermissionBasic struct {
	ID   uint64 `json:"id" gorm:"primaryKey"`
	Name string `json:"name" gorm:"column:name;size:100"`
	Code string `json:"code" gorm:"column:code;uniqueIndex"`
}

// From 从 Permission 复制字段值
func (t *PermissionBasic) From(src *Permission) {
	t.ID = src.ID
	t.Name = src.Name
	t.Code = src.Code
}

// NewPermissionBasic 从 Permission 创建 PermissionBasic
func NewPermissionBasic(src *Permission) PermissionBasic {
	var result PermissionBasic
	result.From(src)
	return result
}

// PermissionDetail 从 Permission Pick 生成
type PermissionDetail struct {
	ID          uint64 `json:"id" gorm:"primaryKey"`
	Name        string `json:"name" gorm:"column:name;size:100"`
	Code        string `json:"code" gorm:"column:code;uniqueIndex"`
	Description string `json:"description" gorm:"column:description"`
	Module      string `json:"module" gorm:"column:module;size:50"`
}

// From 从 Permission 复制字段值
func (t *PermissionDetail) From(src *Permission) {
	t.ID = src.ID
	t.Name = src.Name
	t.Code = src.Code
	t.Description = src.Description
	t.Module = src.Module
}

// NewPermissionDetail 从 Permission 创建 PermissionDetail
func NewPermissionDetail(src *Permission) PermissionDetail {
	var result PermissionDetail
	result.From(src)
	return result
}

// ================ omitgen ================

// AccountPublic 从 Account Omit 生成
type AccountPublic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Name      string    `json:"name" gorm:"column:name;size:100"`
	Email     string    `json:"email" gorm:"column:email;uniqueIndex"`
	Phone     string    `json:"phone" gorm:"column:phone;size:20"`
	Address   string    `json:"address" gorm:"column:address;size:255"`
	Balance   float64   `json:"balance" gorm:"column:balance"`
	Status    string    `json:"status" gorm:"column:status;size:20"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Account 复制字段值
func (t *AccountPublic) From(src *Account) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.Phone = src.Phone
	t.Address = src.Address
	t.Balance = src.Balance
	t.Status = src.Status
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewAccountPublic 从 Account 创建 AccountPublic
func NewAccountPublic(src *Account) AccountPublic {
	var result AccountPublic
	result.From(src)
	return result
}

// AccountSafe 从 Account Omit 生成
type AccountSafe struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Name      string    `json:"name" gorm:"column:name;size:100"`
	Email     string    `json:"email" gorm:"column:email;uniqueIndex"`
	Phone     string    `json:"phone" gorm:"column:phone;size:20"`
	Address   string    `json:"address" gorm:"column:address;size:255"`
	Status    string    `json:"status" gorm:"column:status;size:20"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Account 复制字段值
func (t *AccountSafe) From(src *Account) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.Phone = src.Phone
	t.Address = src.Address
	t.Status = src.Status
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewAccountSafe 从 Account 创建 AccountSafe
func NewAccountSafe(src *Account) AccountSafe {
	var result AccountSafe
	result.From(src)
	return result
}

// PermissionPublic 从 Permission Omit 生成
type PermissionPublic struct {
	ID          uint64    `json:"id" gorm:"primaryKey"`
	Name        string    `json:"name" gorm:"column:name;size:100"`
	Code        string    `json:"code" gorm:"column:code;uniqueIndex"`
	Description string    `json:"description" gorm:"column:description"`
	Module      string    `json:"module" gorm:"column:module;size:50"`
	CreatedAt   time.Time `json:"created_at" gorm:"autoCreateTime"`
}

// From 从 Permission 复制字段值
func (t *PermissionPublic) From(src *Permission) {
	t.ID = src.ID
	t.Name = src.Name
	t.Code = src.Code
	t.Description = src.Description
	t.Module = src.Module
	t.CreatedAt = src.CreatedAt
}

// NewPermissionPublic 从 Permission 创建 PermissionPublic
func NewPermissionPublic(src *Permission) PermissionPublic {
	var result PermissionPublic
	result.From(src)
	return result
}
