// Code generated by gogen. DO NOT EDIT.
package specialpkg

import "time"

// ================ pickgen ================

// ConfigBasic 从 Config Pick 生成
type ConfigBasic struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Key   string `json:"key" gorm:"column:key;uniqueIndex"`
	Value string `json:"value" gorm:"column:value"`
}

// From 从 Config 复制字段值
func (t *ConfigBasic) From(src *Config) {
	t.ID = src.ID
	t.Key = src.Key
	t.Value = src.Value
}

// NewConfigBasic 从 Config 创建 ConfigBasic
func NewConfigBasic(src *Config) ConfigBasic {
	var result ConfigBasic
	result.From(src)
	return result
}

// SettingsCore 从 Settings Pick 生成
type SettingsCore struct {
	ID      uint64 `json:"id" gorm:"primaryKey"`
	Name    string `json:"name" gorm:"column:name;size:100"`
	Enabled bool   `json:"enabled" gorm:"column:enabled"`
}

// From 从 Settings 复制字段值
func (t *SettingsCore) From(src *Settings) {
	t.ID = src.ID
	t.Name = src.Name
	t.Enabled = src.Enabled
}

// NewSettingsCore 从 Settings 创建 SettingsCore
func NewSettingsCore(src *Settings) SettingsCore {
	var result SettingsCore
	result.From(src)
	return result
}

// ================ omitgen ================

// ConfigPublic 从 Config Omit 生成
type ConfigPublic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Key       string    `json:"key" gorm:"column:key;uniqueIndex"`
	Value     string    `json:"value" gorm:"column:value"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Config 复制字段值
func (t *ConfigPublic) From(src *Config) {
	t.ID = src.ID
	t.Key = src.Key
	t.Value = src.Value
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewConfigPublic 从 Config 创建 ConfigPublic
func NewConfigPublic(src *Config) ConfigPublic {
	var result ConfigPublic
	result.From(src)
	return result
}
