// Code generated by gogen. DO NOT EDIT.
package basic

import "time"

// ================ pickgen ================

// ProductSummary 从 Product Pick 生成
type ProductSummary struct {
	ID    uint64  `json:"id" gorm:"primaryKey"`
	Name  string  `json:"name" gorm:"column:name;size:200"`
	Price float64 `json:"price" gorm:"column:price"`
}

// From 从 Product 复制字段值
func (t *ProductSummary) From(src *Product) {
	t.ID = src.ID
	t.Name = src.Name
	t.Price = src.Price
}

// NewProductSummary 从 Product 创建 ProductSummary
func NewProductSummary(src *Product) ProductSummary {
	var result ProductSummary
	result.From(src)
	return result
}

// UserBasic 从 User Pick 生成
type UserBasic struct {
	ID    uint64 `json:"id" gorm:"primaryKey"`
	Name  string `json:"name" gorm:"column:name;size:100"`
	Email string `json:"email" gorm:"column:email;uniqueIndex"`
}

// From 从 User 复制字段值
func (t *UserBasic) From(src *User) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
}

// NewUserBasic 从 User 创建 UserBasic
func NewUserBasic(src *User) UserBasic {
	var result UserBasic
	result.From(src)
	return result
}

// UserProfile 从 User Pick 生成
type UserProfile struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Name      string    `json:"name" gorm:"column:name;size:100"`
	Email     string    `json:"email" gorm:"column:email;uniqueIndex"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 User 复制字段值
func (t *UserProfile) From(src *User) {
	t.ID = src.ID
	t.Name = src.Name
	t.Email = src.Email
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewUserProfile 从 User 创建 UserProfile
func NewUserProfile(src *User) UserProfile {
	var result UserProfile
	result.From(src)
	return result
}

// ================ omitgen ================

// ArticlePreview 从 Article Omit 生成
type ArticlePreview struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Title     string    `json:"title" gorm:"column:title;size:255"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Article 复制字段值
func (t *ArticlePreview) From(src *Article) {
	t.ID = src.ID
	t.Title = src.Title
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewArticlePreview 从 Article 创建 ArticlePreview
func NewArticlePreview(src *Article) ArticlePreview {
	var result ArticlePreview
	result.From(src)
	return result
}

// ArticlePublic 从 Article Omit 生成
type ArticlePublic struct {
	ID        uint64    `json:"id" gorm:"primaryKey"`
	Title     string    `json:"title" gorm:"column:title;size:255"`
	Content   string    `json:"content" gorm:"column:content;type:text"`
	CreatedAt time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// From 从 Article 复制字段值
func (t *ArticlePublic) From(src *Article) {
	t.ID = src.ID
	t.Title = src.Title
	t.Content = src.Content
	t.CreatedAt = src.CreatedAt
	t.UpdatedAt = src.UpdatedAt
}

// NewArticlePublic 从 Article 创建 ArticlePublic
func NewArticlePublic(src *Article) ArticlePublic {
	var result ArticlePublic
	result.From(src)
	return result
}

// ProductDetail 从 Product Omit 生成
type ProductDetail struct {
	ID          uint64  `json:"id" gorm:"primaryKey"`
	Name        string  `json:"name" gorm:"column:name;size:200"`
	Description string  `json:"description" gorm:"column:description;type:text"`
	Price       float64 `json:"price" gorm:"column:price"`
	Stock       int     `json:"stock" gorm:"column:stock"`
}

// From 从 Product 复制字段值
func (t *ProductDetail) From(src *Product) {
	t.ID = src.ID
	t.Name = src.Name
	t.Description = src.Description
	t.Price = src.Price
	t.Stock = src.Stock
}

// NewProductDetail 从 Product 创建 ProductDetail
func NewProductDetail(src *Product) ProductDetail {
	var result ProductDetail
	result.From(src)
	return result
}
