// Code generated by gogen. DO NOT EDIT.
package wildcard

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// 流程图：
// ```
//                                                 ┌──▶ Ready(Running) 🔁
//                                                 │
//                                                 │
//                           ┌──▶ Ready(Stopped) ──┤
//                           │                     │                        ┌── <COMMIT> ──▶ Terminated
//                           │                     │                        │
//                           │                     └──▶ Terminating (via) ──┤
//                           │                                              │
//                           │                                              └── <REJECT> ──▶ Ready(Stopped) 🔁
// Init ──▶ Ready(Running) ──┤
//                           │
//                           │
//                           │
//                           │                        ┌── <COMMIT> ──▶ Terminated
//                           │                        │
//                           └──▶ Terminating (via) ──┤
//                                                    │
//                                                    └── <REJECT> ──▶ Ready(Running) 🔁
// ```

// MachinePhase 阶段枚举
type MachinePhase string

const (
	MachinePhaseInit        MachinePhase = "Init"
	MachinePhaseReady       MachinePhase = "Ready"
	MachinePhaseTerminated  MachinePhase = "Terminated"
	MachinePhaseTerminating MachinePhase = "Terminating"
)

var MachinePhaseEnums = struct {
	Init        MachinePhase
	Ready       MachinePhase
	Terminated  MachinePhase
	Terminating MachinePhase
}{
	Init:        MachinePhaseInit,
	Ready:       MachinePhaseReady,
	Terminated:  MachinePhaseTerminated,
	Terminating: MachinePhaseTerminating,
}

// MachineStatus 状态枚举
type MachineStatus string

const (
	MachineStatusNone    MachineStatus = ""
	MachineStatusRunning MachineStatus = "Running"
	MachineStatusStopped MachineStatus = "Stopped"
)

var MachineStatusEnums = struct {
	None    MachineStatus
	Running MachineStatus
	Stopped MachineStatus
}{
	None:    MachineStatusNone,
	Running: MachineStatusRunning,
	Stopped: MachineStatusStopped,
}

// MachineStage 阶段（Phase + Status）
type MachineStage struct {
	Phase  MachinePhase  `json:"phase"`
	Status MachineStatus `json:"status"`
}

// 预定义阶段
var (
	StageMachineInit         = MachineStage{MachinePhaseInit, MachineStatusNone}
	StageMachineReadyRunning = MachineStage{MachinePhaseReady, MachineStatusRunning}
	StageMachineReadyStopped = MachineStage{MachinePhaseReady, MachineStatusStopped}
	StageMachineTerminated   = MachineStage{MachinePhaseTerminated, MachineStatusNone}
	StageMachineTerminating  = MachineStage{MachinePhaseTerminating, MachineStatusNone}
)

// MachinePendingTransition 审批事务
type MachinePendingTransition struct {
	From     MachineStage `json:"from"`
	To       MachineStage `json:"to"`
	Fallback MachineStage `json:"fallback"`
}

// MachineState 完整状态
type MachineState struct {
	Current MachineStage              `json:"current"`
	Pending *MachinePendingTransition `json:"pending,omitempty"`
}

// MachineStateColumns 数据库存储结构
type MachineStateColumns struct {
	Phase   MachinePhase                                  `gorm:"column:phase" json:"phase"`
	Status  MachineStatus                                 `gorm:"column:status" json:"status"`
	Pending datatypes.JSONType[*MachinePendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s MachineState) ToColumns() MachineStateColumns {
	return MachineStateColumns{
		Phase:   s.Current.Phase,
		Status:  s.Current.Status,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c MachineStateColumns) ToState() MachineState {
	return MachineState{
		Current: MachineStage{Phase: c.Phase, Status: c.Status},
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrMachineInvalidTransition  = errors.New("invalid transition")
	ErrMachineApprovalInProgress = errors.New("approval in progress")
	ErrMachineNotInApproval      = errors.New("not in approval")
)

func (s MachineState) TransitionTo(to MachineStage, withApproval bool) (MachineState, error) {
	switch s.Current {
	case StageMachineInit:
		switch to {
		case StageMachineReadyRunning:
			return MachineState{Current: to}, nil
		}
	case StageMachineReadyRunning:
		switch to {
		case StageMachineReadyStopped:
			return MachineState{Current: to}, nil
		case StageMachineTerminated:
			if s.Pending != nil {
				return s, ErrMachineApprovalInProgress
			}
			return MachineState{Current: StageMachineTerminating, Pending: &MachinePendingTransition{From: s.Current, To: to, Fallback: StageMachineReadyRunning}}, nil
		}
	case StageMachineReadyStopped:
		switch to {
		case StageMachineReadyRunning:
			return MachineState{Current: to}, nil
		case StageMachineTerminated:
			if s.Pending != nil {
				return s, ErrMachineApprovalInProgress
			}
			return MachineState{Current: StageMachineTerminating, Pending: &MachinePendingTransition{From: s.Current, To: to, Fallback: StageMachineReadyStopped}}, nil
		}
	}
	return s, ErrMachineInvalidTransition
}

func (s MachineState) Commit() (MachineState, error) {
	if s.Pending == nil {
		return s, ErrMachineNotInApproval
	}
	return MachineState{Current: s.Pending.To}, nil
}

func (s MachineState) Reject() (MachineState, error) {
	if s.Pending == nil {
		return s, ErrMachineNotInApproval
	}
	return MachineState{Current: s.Pending.Fallback}, nil
}

func (s MachineState) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s MachineState) ValidTransitions() []MachineStage {
	switch s.Current {
	case StageMachineInit:
		return []MachineStage{StageMachineReadyRunning}
	case StageMachineReadyRunning:
		return []MachineStage{StageMachineReadyStopped, StageMachineTerminated}
	case StageMachineReadyStopped:
		return []MachineStage{StageMachineReadyRunning, StageMachineTerminated}
	}
	return nil
}
