// Code generated by gogen. DO NOT EDIT.
package wildcard

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// Phase 阶段枚举
type Phase string

const (
	PhaseNone             Phase = "none"
	PhaseCreated          Phase = "created"
	PhaseCreationRejected Phase = "creation_rejected"
)

var PhaseEnums = struct {
	None             Phase
	Created          Phase
	CreationRejected Phase
}{
	None:             PhaseNone,
	Created:          PhaseCreated,
	CreationRejected: PhaseCreationRejected,
}

// Stage 阶段（Phase + Status）
type Stage = Phase

// 预定义阶段
var (
	StageNone             = PhaseNone
	StageCreated          = PhaseCreated
	StageCreationRejected = PhaseCreationRejected
)

// PendingTransition 审批事务
type PendingTransition struct {
	From     Stage `json:"from"`
	To       Stage `json:"to"`
	Fallback Stage `json:"fallback"`
}

// State 完整状态
type State struct {
	Current Stage              `json:"current"`
	Pending *PendingTransition `json:"pending,omitempty"`
}

// StateColumns 数据库存储结构
type StateColumns struct {
	Phase   Phase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*PendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s State) ToColumns() StateColumns {
	return StateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c StateColumns) ToState() State {
	return State{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrInvalidTransition  = errors.New("invalid transition")
	ErrApprovalInProgress = errors.New("approval in progress")
	ErrNotInApproval      = errors.New("not in approval")
)

func (s State) TransitionTo(to Stage, withApproval bool) (State, error) {
	switch s.Current {
	case StageNone:
		switch to {
		case StageCreated:
			if withApproval {
				if s.Pending != nil {
					return s, ErrApprovalInProgress
				}
				return State{Current: StageNone, Pending: &PendingTransition{From: s.Current, To: to, Fallback: StageCreationRejected}}, nil
			}
			return State{Current: to}, nil
		}
	}
	return s, ErrInvalidTransition
}

func (s State) Commit() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.To}, nil
}

func (s State) Reject() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.Fallback}, nil
}

func (s State) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s State) ValidTransitions() []Stage {
	switch s.Current {
	case StageNone:
		return []Stage{StageCreated}
	}
	return nil
}
