// Code generated by gogen. DO NOT EDIT.
package wildcard

import (
	"errors"

	"gorm.io/datatypes"
)

// ================ stateflow ================

// 流程图：
// ```
//                                                                                                        ┌──▶ deployed
//                                                                                                        │
//                                           ┌── <COMMIT> ──▶ creation_initiated ──▶ creation_submitted ──┤
//                                           │                                                            │
//                                           │                                                            └──▶ deploy_failed
//                         ┌──▶ none (via) ──┤
//                         │                 │
//                         │                 │
//                         │                 └── <REJECT> ──▶ none 🔁
// none ──▶ <?APPROVAL?> ──┤
//                         │
//                         │                                                ┌──▶ deployed
//                         │                                                │
//                         └──▶ creation_initiated ──▶ creation_submitted ──┤
//                                                                          │
//                                                                          └──▶ deploy_failed
// ```

// Phase 阶段枚举
type Phase string

const (
	PhaseNone              Phase = "none"
	PhaseCreationInitiated Phase = "creation_initiated"
	PhaseCreationSubmitted Phase = "creation_submitted"
	PhaseDeployed          Phase = "deployed"
	PhaseDeployFailed      Phase = "deploy_failed"
)

var PhaseEnums = struct {
	None              Phase
	CreationInitiated Phase
	CreationSubmitted Phase
	Deployed          Phase
	DeployFailed      Phase
}{
	None:              PhaseNone,
	CreationInitiated: PhaseCreationInitiated,
	CreationSubmitted: PhaseCreationSubmitted,
	Deployed:          PhaseDeployed,
	DeployFailed:      PhaseDeployFailed,
}

// Stage 阶段（Phase + Status）
type Stage = Phase

// 预定义阶段
var (
	StageNone              = PhaseNone
	StageCreationInitiated = PhaseCreationInitiated
	StageCreationSubmitted = PhaseCreationSubmitted
	StageDeployed          = PhaseDeployed
	StageDeployFailed      = PhaseDeployFailed
)

// PendingTransition 审批事务
type PendingTransition struct {
	From     Stage `json:"from"`
	To       Stage `json:"to"`
	Fallback Stage `json:"fallback"`
}

// State 完整状态
type State struct {
	Current Stage              `json:"current"`
	Pending *PendingTransition `json:"pending,omitempty"`
}

// StateColumns 数据库存储结构
type StateColumns struct {
	Phase   Phase                                  `gorm:"column:phase" json:"phase"`
	Pending datatypes.JSONType[*PendingTransition] `gorm:"column:pending" json:"pending"`
}

func (s State) ToColumns() StateColumns {
	return StateColumns{
		Phase:   s.Current,
		Pending: datatypes.NewJSONType(s.Pending),
	}
}

func (c StateColumns) ToState() State {
	return State{
		Current: c.Phase,
		Pending: c.Pending.Data(),
	}
}

// 错误定义
var (
	ErrInvalidTransition  = errors.New("invalid transition")
	ErrApprovalInProgress = errors.New("approval in progress")
	ErrNotInApproval      = errors.New("not in approval")
)

func (s State) TransitionTo(to Stage, withApproval bool) (State, error) {
	switch s.Current {
	case StageNone:
		switch to {
		case StageCreationInitiated:
			if withApproval {
				if s.Pending != nil {
					return s, ErrApprovalInProgress
				}
				return State{Current: StageNone, Pending: &PendingTransition{From: s.Current, To: to, Fallback: StageNone}}, nil
			}
			return State{Current: to}, nil
		}
	case StageCreationInitiated:
		switch to {
		case StageCreationSubmitted:
			return State{Current: to}, nil
		}
	case StageCreationSubmitted:
		switch to {
		case StageDeployed:
			return State{Current: to}, nil
		case StageDeployFailed:
			return State{Current: to}, nil
		}
	}
	return s, ErrInvalidTransition
}

func (s State) Commit() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.To}, nil
}

func (s State) Reject() (State, error) {
	if s.Pending == nil {
		return s, ErrNotInApproval
	}
	return State{Current: s.Pending.Fallback}, nil
}

func (s State) IsApprovalPending() bool {
	return s.Pending != nil
}

func (s State) ValidTransitions() []Stage {
	switch s.Current {
	case StageNone:
		return []Stage{StageCreationInitiated}
	case StageCreationInitiated:
		return []Stage{StageCreationSubmitted}
	case StageCreationSubmitted:
		return []Stage{StageDeployed, StageDeployFailed}
	}
	return nil
}
